### ISSUE TITLE
undoManager issue with text deletion

### ISSUE THREAD

**Issue by calibr** [yjs/yjs#162]
- add a character to YText
- delete the character
- call undo - works fine, character gets returned to the YText's delta
- call undo again - does not work, the character is still in the delta, but must be removed

code reproduction:

```
const Y = require('yjs')

const doc = new Y.Doc()
const text = doc.get('text', Y.Text)
const undoManager = new Y.UndoManager(text)

text.applyDelta([{ insert: 'a' }])
undoManager.stopCapturing()
text.applyDelta([{ delete: 1 }])
undoManager.stopCapturing()
undoManager.undo()
console.log(text.toDelta()) // prints [ { insert: 'a' } ] - it is fine
undoManager.undo()
console.log(text.toDelta()) // prints [ { insert: 'a' } ] again, it is wrong
```

when I remove `&& !struct.deleted` from this condition https://github.com/y-js/yjs/blob/master/src/utils/UndoManager.js#L65 it starts to work fine and the tests seems to pass.

**Comment by dmonad** [comment]
Is this still an issues @calibr ?

**Comment by dmonad** [comment]
You were right about this. I added some tests and also covered the case that the struct is already deleted.
