### ISSUE TITLE
Doc update not triggered on new line delta

### ISSUE THREAD

**Issue by estebanprimost** [yjs/yjs#166]
Hi @dmonad, I'm using latest version of `Yjs` with `Y.Text` as shared type. When a new line delta (with a retain operation) is applied via `Y.Text.applyDelta()` function, the `Y.Doc.on('update', fn)` is not being triggered. 
Example code to reproduce it:
```javascript
const Y = require("yjs");

const doc = new Y.Doc();

doc.on("update", update => {
  document.body.innerText += `DOC update: ${doc.getText("content").toString()}\n`;
});

doc.getText("content").applyDelta([{ insert: "B" }]);

// Update not triggered here:
doc.getText("content").applyDelta([{ retain: 1 }, { insert: "\n" }]);

doc.getText("content").applyDelta([{ insert: "A\n" }]);
```
[CodeSandbox here too](https://codesandbox.io/s/silent-fire-tqpo7).

Is this a normal behavior?

As fallback I'm testing if a new line is being inserted and using `Y.Text.insert(index, content)` function.

Thanks and great work with the new version of `Yjs` btw!.

**Comment by dmonad** [comment]
Hey @estebanprimost,

Unfortunately we have a very weird implementation of the delta API to stay with `y-quill` (the main reason this API was written).

QuillJs always starts with an empty line and must always end with an empty line. Therefore the delta API currently just ignores the last newline character. 

You bring up a valid concern. This shouldn't be part of the Yjs API. We should fix the newline problem in y-quill and fix the delta API in Yjs.

**Comment by estebanprimost** [comment]
Thanks for your answer @dmonad!
