### ISSUE TITLE
Inconsistent order of arguments in Y.Map vs. documentation

### ISSUE THREAD

**Issue by istvank** [yjs/yjs#171]
The README documentation says the Y.Map type exposes a `f(key, value)` iterator, however, the source code in https://github.com/yjs/yjs/blob/ece4841b5c503ae4bac89c3d451d182c9ba3d958/src/types/YMap.js#L150
apparently does `f(value, key)`. Am I missing something!? The documentation for Y.Array seems correct. If you confirm, I am more than happy to offer a PR. :grinning:

**Comment by dmonad** [comment]
Thanks @istvank! My intuition also wants to use `f(key, value)`. But this should be consistent with the native Array/Map types. So `f(value, key)` is correct. Thanks for offering a PR for fixing the README :slightly_smiling_face:
