### ISSUE TITLE
Can't install y-websockets-server on MacOS

### ISSUE THREAD

**Issue by micrology** [yjs/yjs#177]
I have been following the instructions at https://github.com/y-js/y-websockets-server for a local installation of the web sockets server, but encountered an error as well as a lot of warnings.  The error is:

```
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
In file included from ../src/validation.cc:15:
In file included from ../node_modules/nan/nan.h:190:
../node_modules/nan/nan_maybe_43_inl.h:88:15: error: no member named 'ForceSet'
      in 'v8::Object'
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
         ~~~  ^
```

This is on MacOS Mojave, 10.14.6.

The exact same issue occurs if I install it globally.

**Comment by istvank** [comment]
Depending on the version of Yjs you're using you don't need to install y-websockets-server anymore. Simply follow the instructions at https://github.com/yjs/y-websocket#start-a-websocket-server

Does this resolve your issue? Please note, that the whole organization has moved to https://github.com/yjs

**Comment by micrology** [comment]
Yes, this was very helpful.  Thanks.



Professor Nigel Gilbert, CBE, ScD, FREng, FAcSS, Professor of Sociology,
University of Surrey, Guildford GU2 7XH, UK. +44 (0)1483 689173

**Comment by istvank** [comment]
That's great to hear! 🎆 I guess @dmonad may close the issue now. 😄
