### ISSUE TITLE
typescript v13?

### ISSUE THREAD

**Issue by tobowers** [yjs/yjs#180]
I see in the readme that yjs has types for typescript, but I don't see them in the src and when I import yjs into a create-react-app --typscript project I'm getting the following error:

```
ould not find a declaration file for module 'yjs'. '/Users/tobowers/code/ipfsdocs/node_modules/yjs/build/yjs.js' implicitly has an 'any' type.
  Try `npm install @types/yjs` if it exists or add a new declaration (.d.ts) file containing `declare module 'yjs';`  TS7016
```

my full tsconfig.json looks like:
```
{
  "compilerOptions": {
    "target": "es2015",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "checkJs": true,
    "jsx": "react",
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true
  },
  "maxNodeModuleJsDepth": 5,
  "include": [
    "src"
  ]
}
```

**Comment by dmonad** [comment]
You also need to include the yjs files in your project now. They broke in one of the previous typescript releases. 

But here are some good news, TypeScript now supports --declaration with --allowjs, so I can finally export proper type declarations for Yjs :-) https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#--declaration-and---allowjs

**Comment by tobowers** [comment]
oh amazing! Thanks!

**Comment by dmonad** [comment]
I even did you one better. I published a stable v13 release :slightly_smiling_face:
