### ISSUE TITLE
The demos at yjs-demos.now.sh appear to be down

### ISSUE THREAD

**Issue by jure** [yjs/yjs#190]
As the title says, the demos hosted on yjs-demos.now.sh appear to be down.

**Comment by jure** [comment]
They're up now, closing.

**Comment by dmonad** [comment]
Actually, now.sh sent me an update that they will soon shut-down the yjs-demos repository because it uses *now v1*. I already updated a lot of the links to the new service at demos.yjs.dev. 

Please let me know if you find any more `*.now.sh` urls.
