### ISSUE TITLE
Flatten document over time

### ISSUE THREAD

**Issue by ISNIT0** [yjs/yjs#196]
Is there a way we can flatten client IDs older than X (2 days or something) into a single update?

At the moment, pages that get a lot of updates (e.g. coronavirustechhandbook.com) become quite large (stored as a YJS update buffer) over time. I'd like to be able to keep the YJS magic for revisions and offline edits for the last two days, but don't mind losing it after that

**Comment by dmonad** [comment]
This would destroy the document integrity. You wouldn't be able to merge a "flattened" document with a non-flattened. Or all parties would need to agree to flatten the document at the same time.

So you need to implement a custom "flatten" strategy, as you already do.

**Comment by ISNIT0** [comment]
I've actually found the way we're currently doing this is not effective. Because all YJS state is lost when doing the flatten (not just old state).
I was thinking it might be possible to merge edits older than 2 days into one clientId, but keep recent edits so we can use fancy YJS features for the active document.

**Comment by dmonad** [comment]
> I was thinking it might be possible to merge edits older than 2 days into one clientId

This is a good idea and theoretically possible, but you'd need a consensus algorithm that defines exactly when these edits are merged. I hope that with the most recent Y.Text fix the document size will stay reasonably small.
