### ISSUE TITLE
Formatting in Y.Text increases update size a lot

### ISSUE THREAD

**Issue by ISNIT0** [yjs/yjs#197]
E.g.
- create new document on JoeDocs.com
- `Y.encodeStateAsUpdate(wave.doc).length` = 2
- Type "how now brown cow"
- `Y.encodeStateAsUpdate(wave.doc).length` = 35
- CMD+A CMD+B (bold all text)
- `Y.encodeStateAsUpdate(wave.doc).length` = 69
- Has nearly doubled the document size

I'm not sure if this is a bug, but it causes various JoeDocs documents to become very large when people add formatting (happens with bullet points etc too).

**Comment by dmonad** [comment]
This is not a bug. This is the intended behavior. Formatting does not always double the size of the document (only when you start with a small document).

Attributes in text are represented as markers. The value of the markers are represented as text, and also need space. Yjs represents formatting attributes as markers:

```json
{bold: true}how now brown cow{bold: false}
```

Then it makes sense that encoding formatting attributes takes up at least `"{bold:true}".length * 2 = 22 byte` more space. The rest is used for Yjs-internal metadata for conflict resolution.

The problem you were experiencing is that some formatting attributes are not deleted after the content in-between has been deleted. So after deleting `"how now brown cow"` the markers should be deleted too. I fixed this issue and others in Yjs@13.0.7. I also ported randomized tests from y-quill to this repository and check on test-completion that no leftover formatting attributes are present.
