### ISSUE TITLE
Slate support

### ISSUE THREAD

**Issue by BitPhinix** [yjs/yjs#202]
**Checklist**

[ ] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
[ ] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Is your feature request related to a problem? Please describe.**
Slate currently lacks a good, scalable collab solution (see [here](https://github.com/ianstormtaylor/slate/issues/259)). There is an implementation based on automerge and one on sharedb but the sharedb implementation is quite hacky and the automerge solution is really slow on large documents.

YJS seems like the ideal solution for this. 

**Describe the solution you'd like**
A first-party integration of YJS. Like https://github.com/yjs/y-prosemirror.

**Describe alternatives you've considered**
- https://github.com/cudr/slate-collaborative (Automerge)
- https://github.com/Immortalin/slate-operational-transform (ShareDB)

**Comment by dmonad** [comment]
Please look here:
https://discuss.yjs.dev/t/slate-js-bindings/59
