### ISSUE TITLE
Inserting Y.Map into Y.Array does not set its doc immediately

### ISSUE THREAD

**Issue by canadaduane** [yjs/yjs#210]
As expected, when setting a new Y.Map as a value of an existing Y.Map whose `doc` is set, the child Y.Map immediately inherits the parent Y.Map's `doc`:

```
const ydoc = new Y.Doc()

const yParentMap = ydoc.getMap('parent')
yParentMap.doc // -> Doc { _observers: ... }
    
const yChildMap = new Y.Map()
yParentMap.set('child', yChildMap)
yChildMap.doc // -> Doc { _observers: ... }
```

However, when inserting a new Y.Map into an existing Y.Array whose `doc` is set, the child Y.Map's `doc` remains null:

```
const ydoc = new Y.Doc()

const yParentArray = ydoc.getArray('parent')
yParentArray.doc // -> Doc { _observers: ... }

const yChildMap = new Y.Map()
yParentArray.insert(0, yChildMap)
yChildMap.doc // -> null
```

I expect that inserting a map into an array would be analogous to setting a map on a map, and therefore the doc should be inherited.

**Environment Information**
 - Firefox 77.0.1
 - Yjs 13.0.4

**Comment by canadaduane** [comment]
Ah! I didn't realize the 2nd argument of Y.Array's `insert` requires an array.

**Comment by canadaduane** [comment]
Yes, this explains the issue I was seeing. Tests check out again.

I wonder if there's a way to let it fail faster. There is no error when inserting a non-array type. 

Ideally I should be using typescript to check errors of this kind. But I'm not at the moment (and probably won't be for the foreseeable future).

**Comment by dmonad** [comment]
I want to support anything iterable as an argument. It is pretty hard to check for that. Unless you have typescript, you won't get error messages for now.
