### ISSUE TITLE
Typescript: YTextEvent not exported and "event.changes.key" property missing.

### ISSUE THREAD

**Issue by BitPhinix** [yjs/yjs#213]
**Checklist**

[x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
[x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
1. Y.YTextEvent is not exported (or at least not in the intex.d.ts)
2. "key" property missing in typescript types for YMapEvent.changes.keys

**To Reproduce**
1. Try to import Y.YTextEvent
2. Try to get the key property on a YMapEvent property

**Environment Information**
-  Typescript, Node

**Comment by dmonad** [comment]
Right, I'll export it in the next release.

**Comment by dmonad** [comment]
The next time please open two separate tickets for two separate issues.

I thought the second issue was related to the first one (the missing type export).

`event.changes.key` does not exist and is nowhere documented

`event.changes.keys` is a `Map`. So you need to get the key using the `.get` method. It works as expected :wink: 

The first issue is now fixed. I will publish a new release in a few minutes.
