### ISSUE TITLE
Y.Doc toJSON

### ISSUE THREAD

**Issue by canadaduane** [yjs/yjs#217]
I didn't see a toJSON() function on Y.Doc, so I implemented one as a separate function:

```
function yDocToJSON(ydoc) {
  const doc = {}

  for (const [k, v] of ydoc.share.entries()) {
    doc[k] = v.toJSON()
  }
  
  return doc
}
```

Does it make sense to add something like this to Y.Doc itself?

**Comment by dmonad** [comment]
Yeah, I think that would be cool :)
