### ISSUE TITLE
Document toJSON API

### ISSUE THREAD

**Issue by ajhyndman** [yjs/yjs#222]
Hi!  I'm excited to dip my feet back into the land of CRDTs after a few years of following from a distance.

This issue is just a quick question.  I noticed that the `.toJSON()` API was added a few days ago, but hasn't been documented yet.  Is that a feature you would like to be documented?

I wouldn't mind proposing a diff, if you think it could be helpful.  :)

**Comment by dmonad** [comment]
Sure, I'd be happy to receive a PR :slightly_smiling_face:
