### ISSUE TITLE
[typescript] typings missing DeltaItem.instert

### ISSUE THREAD

**Issue by akosyakov** [yjs/yjs#227]
> Please save me some time and use the following template. In 90% of all issues I can't reproduce the problem because I don't know what exactly you are doing, in which environment, or which y-* version is responsible. Just use the following template even if you think the problem is obvious.

**Checklist**

* [ ] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [ ] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**

**To Reproduce**
3. Open console

**Expected behavior**

**Screenshots**

**Environment Information**
 - Browser / Node.js [e.g. Chrome, Firefox, Node.js]
 - Yjs version and the versions of the y-* modules you are using [e.g. yjs v13.0.1, y-webrtc v1.2.1]. Use `npm ls yjs` to find out the exact version you are using.

**Additional context**

**Comment by akosyakov** [comment]
Hi, I meant the property is missing here: https://github.com/yjs/yjs/blob/6e3b708599ecfdd6c9c7f5af72debabbe74cc1af/src/types/YText.js#L500-L506, sorry thought the issues title was self explaining.

**Comment by dmonad** [comment]
Right. Thanks!

**Comment by dmonad** [comment]
This will be fixed in the next release
