### ISSUE TITLE
how to remove type from doc

### ISSUE THREAD

**Issue by akosyakov** [yjs/yjs#229]
I was expecting something like:
```ts
const text = doc.getText(resource);
// by ID
doc.delete(resource);
// OR on text directly
text.dispose();
```

Or it's recommended to create a doc per a text?

**Comment by dmonad** [comment]
You can create one doc per text, or you can create a folder structure using Yjs types. https://github.com/yjs/yjs#example-nest-types

Top-level data types (the data types you "define" on a document) can't be deleted. But you can delete their content. E.g. doc.getText().delete(0, text.length). 

Please use discuss.yjs.dev next time for questions. I use github issues for tracking my work.
