### ISSUE TITLE
Typings for YXmlFragment, YXmlElement seems to be incomplete.

### ISSUE THREAD

**Issue by BitPhinix** [yjs/yjs#231]
**Describe the bug**
The "get" function mentioned in the readme seems to be missing in the typescript typings for YXmlFragment, YXmlElement.

**Screenshots**
![image](https://user-images.githubusercontent.com/13185548/89926821-ac301180-dc05-11ea-8f95-f6f42de4a7b6.png)

**Comment by ellisonbg** [comment]
Hi @BitPhinix I was starting to look at this issue. In the current APIs I don't see a get method. Do you mean `getAttribute`?

https://github.com/yjs/yjs/blob/main/src/types/YXmlElement.js#L129

**Comment by BitPhinix** [comment]
It cloud be that just the readme is incorrect, haven't looked for it in the codebase yet. If you take a look at the Readme, you can clearly find it under both the Y.XmlFragment and Y.XmlElement documentation [here](https://github.com/yjs/yjs/blob/main/README.md#api). I'm planning to replace the Y.Map, Y.Array structure currently used in [slate-yjs](https://github.com/BitPhinix/slate-yjs) with Y.XmlElements / Y.XmlFragments for performance reasons (and also simply because it's cleaner)

**Comment by ellisonbg** [comment]
@BitPhinix I will try to have a look - it could be that the docs are out of date.

**Comment by ellisonbg** [comment]
Here is PR that fixes the API docs: #249
