### ISSUE TITLE
Subdocuments

### ISSUE THREAD

**Issue by dmonad** [yjs/yjs#234]
This ticket keeps track of the *subdocument* feature. 

*Subdocuments* will allow you to include a document into another document. Subdocuments will allow you to manage large datasets, organize an overview of documents that are available for a user (e.g. list of owned documents), handle authentication/authorization over a single entry point, and sync multiple documents over a single connection.

We will introduce a new type `Y.SubDoc(id?: string)` that can be embedded into a `Y.Doc` to refer to another document. An immediate use-case is to create a list of notes owned by a user. Each note could be represented as a `Y.SubDoc` that is only loaded when needed.

By default, subdocuments are empty until they receive content from the provider.

Subdocuments are loaded lazily after they have been accessed. A `SubDoc` can be destroyed `subdoc.destroy()` to free all used memory and destroy existing data bindings (similarly to `ydoc.destroy()`). The document can be accessed again to force the provider to load the content again.

Providers (e.g. y-websocket, y-indexeddb) can listen to the `subdoc` event that is fired when a subdocument is accessed. This event is fired once, and providers are responsible to sync the document as well as the root document.

For convenience, a subdoc can be marked as "synced" by any provider to indicate that some content has been loaded from the network or database.

## Sample code

```js
const ydoc = new Y.Doc()

// Listen to the `subdoc` event that is fired when a subdoc is loaded.
// This should be handled by the provider
ydoc.on('subdoc', (subdoc) => {
  console.log('subdoc accessed. id: ', subdoc.id)
})

// you can't create subdocs as top-level documents
ydoc.get('subdoc', Y.SubDoc) // Error! not allowed

const map = ydoc.getMap('mymap')

map.set('my sub doc', new Y.SubDoc('test'))
// subdoc is synced as soon as it is first accessed
map.get('my sub doc') // => "subdoc accessed. id: 'test'
const subdoc =map.get('my sub doc') // accessed again, but no event is fired

// subdoc is still empty. Wait for the `synced` event to access available data
subdoc.on('synced', () => { /* now all content is synced */ })

// destroy subdoc and all contained types
subdoc.destroy()

// retrieve subdoc again, the event is fired because the old subdoc is no longer synced
const subdoc2 =map.get('my sub doc') // => "subdoc accessed. id: 'test'
```

## Example to lazy-load documents using y-websocket

An easy method implement lazy-loading with the existing providers is to create a new provider instance when a subdoc is loaded:

```js
doc.on('subdoc', subdoc => {
  // sync subdoc over the available 
  new WebRTCProvider(subdoc, subdoc.id)
})
```

In the above example, we reused `doc.id` to refer to a room-name. Of course, subdocuments do not need to adhere to this concept. 

A more involved connector (This is what I wanted to achieve with `ydb`) might want to sync all subdocs efficiently over a single connection. In a peer-to-peer world, is is hard to sync many documents with different permissions with many different clients. We are currently only able to sync a single document at a time because each document has different permissions. I believe that subdocs might be the answer to sync many documents.

Projects are still organized under specific organizations or a folder. If we want to share permission for an organization/folder/project, we can model the entity as a single Y.Doc that contains SubDocs that contain the actual project content. Most productive work is organized in organizations to manage related projects (a project in this context might be the work on a javascript library, or a latex paper. Projects typically consist of many different Yjs documents - e.g. a Y.Doc for each text file). As an example of Slack and GitHub, we can observe that people are part of a few organizations. Organizations handle specific permissions. Projects sometimes have more strict permissions. Syncing many documents will get easier if the Yjs documents reflect the permission structure, instead of having separate permissions for every single document. Instead of asking remote peers if they can sync document XXX, we can now ask if they want to sync organization YYY. This will allow us to sync a very large amount of documents in a few small requests.

## API

`new Y.SubDoc(id?: string [, opts: any])` - Create a new SubDoc type. SubDoc inherits everything from `Y.Doc`. By default, id is a randomly generated GUID. Optionally, you can name the document, or refer to an existing document. `opts` is another optional parameter that allows users to store credentials, or additional data related to the document.

`.id` - the id of the subdoc, used to identify it and distinguish it from other documents
`.opts` - additional data that is stored with the document.
`.on('synced', ev => ..)` - fired when the document has been synced by a provider
`.synced` - Whether the document is synced with other clients
`.unload` - Unload the document

## Open questions
* Should we rename the `subdoc` event to `subdoc-load` and have another event `subdoc` that is fired when a subdoc is added to the document (either by remote or local change). The providers might want to sync subdocs before they are accessed.
* How to retrieve all available subdocs from a document.
* The idea was to lazy-load documents as soon as they are accessed. But I think it makes more sense to load documents explicitly with `subdoc.load()` so that the provider fetches data. Another advantage is that `subdoc.load()` could return a Promise that resolves when all providers loaded content (similarly to the existing `synced` event).

**Comment by calibr** [comment]
> The idea was to lazy-load documents as soon as they are accessed. But I think it makes more sense to load documents explicitly with subdoc.load() so that the provider fetches data. Another advantage is that subdoc.load() could return a Promise that resolves when all providers loaded content (similarly to the existing synced event).

agree that this idea has more sense because a client application will probably always know when subdocument is accessed and will be able to call `.load` on it itself

> How to retrieve all available subdocs from a document.

that is a good feature to have in yjs core, one possible use case is retrieving and loading all the subdocuments immediately after the main document is loaded

**Comment by dmonad** [comment]
> that is a good feature to have in yjs core, one possible use case is retrieving and loading all the subdocuments immediately after the main document is loaded

Right. I also plan to adapt the providers to update documents without loading them to memory. For this I plan to implement a merge function (`merged = merge(update1, update2)`) that can merge any document updates. The providers (y-indexeddb, y-websocket, ..) can then sync documents without actually loading them to memory.

**Comment by dmonad** [comment]
I simplified the approach and added documentation to the new documentation site: https://docs.yjs.dev/api/subdocuments

@calibr You can now start using the subdocs feature in Yjs@13.4.0-0 (you need to explicitly define this version in package.json). 

Let me know what you think!

I've been prototyping a lot with the above approach and I think it does everything that I want it to do. Next I want to have a look at pushpin, because apparently they implemented a similar feature.

**Comment by dmonad** [comment]
This feature is implemented. Seems everyone is happy. I'm happy. That's good.

**Comment by disarticulate** [comment]
over at yjs/y-webrtc I'm getting a transaction where subdocsAdded and subdocsRemoved is missing on the transaction

I'll file a report there, but just incase there's something missing in the main package:
```
cleanupTransactions (yjs.mjs?7428:3043)
cleanupTransactions (yjs.mjs?7428:3053)
transact (yjs.mjs?7428:3092)
readUpdateV2 (yjs.mjs?7428:1555)
applyUpdateV2 (yjs.mjs?7428:1587)
applyUpdate (yjs.mjs?7428:1601)
readSyncStep2 (sync.js?a72f:82)
readSyncMessage (sync.js?a72f:116)
readMessage (y-webrtc.js?9b73:76)
(anonymous) (y-webrtc.js?9b73:333)
(anonymous) (mutex.js?c98a:35)
(anonymous) (y-webrtc.js?9b73:332)
Promise.then (async)
Room._bcSubscriber (y-webrtc.js?9b73:331)
eval (broadcastchannel.js?fadf:104)
publish (broadcastchannel.js?fadf:104)
eval (y-webrtc.js?9b73:249)
eval (mutex.js?c98a:35)
eval (y-webrtc.js?9b73:248)
Promise.then (async)
broadcastBcMessage (y-webrtc.js?9b73:247)
connect (y-webrtc.js?9b73:391)
eval (y-webrtc.js?9b73:579)
Promise.then (async)
WebrtcProvider (y-webrtc.js?9b73:576)
whenSynced (Manifest.js?bba8:46)
{...}
```

**Comment by dmonad** [comment]
Hi @disarticulate ,

Can you please open another ticket and explain exactly what kind of error message you are getting. 

> it isn't happening every time which is odd. The first time through, I get the y-webrtc origin of Room. The second time through, the missing subdocs is gone.

There is a issue template that you would need to fill out. But it kinda looks like you have two different Yjs versions installed (one really old one that doesn't support subdocuments yet).

**Comment by disarticulate** [comment]
A full reinstall fixed the issue, but i'll open up a ticket so you can flag it. I remember there's something that automatically reports mismatches.
