### ISSUE TITLE
UndoManager double undo issue

### ISSUE THREAD

**Issue by CGNonofr** [yjs/yjs#240]
The UndoManager seems to produce an incorrect internal state sometime.

A minimal code reproducing the issue:

```javascript
const Y = require('yjs')

const doc = new Y.Doc()
const text = doc.getText()
text.insert(0, '1221')

const manager = new Y.UndoManager(text)

text.insert(2, '3')
text.insert(3, '3')

manager.undo()
manager.undo()

text.insert(2, '3')

console.log(text.toString())
```

The initial text is `1221`, when inserting `3` at position 2 and 3, the text is now `123321`.

However, after applying 2 changes, then undoing them, if I apply the same transformation (insert `3` on position 2), the result is now `31221` (my insertion is done at the wrong place, at the start, instead of the second position)

Am I doing something wrong?

**Comment by dmonad** [comment]
Hi @CGNonofr ,

please use the bug template even if you think it doesn't apply to you. I can't reproduce your issue because I don't know the Yjs version you are using. 

It is working correctly here: https://stackblitz.com/edit/y-bug-240?file=index.ts

**Comment by CGNonofr** [comment]
Here is the issue using your template: https://github.com/yjs/yjs/issues/241

For a reason I don't understand, stackblitz only use Yjs@13.2.0, and the bug seems to exist on most recent versions (at least v13.3.2)
