### ISSUE TITLE
Python Implementation of the Y.js Server?

### ISSUE THREAD

**Issue by echarles** [yjs/yjs#261]
Hi, I am working on the Jupyter Realtime Collaboration project (https://github.com/jupyterlab/rtc) and one of the requirement is to avoid Node.js as dependency for the user (we set Python only as dependency).

I understand that the Y.js Server requires Node.js (e.g. https://github.com/yjs/y-websocket).

Are there any plan or ways to have a Python implementation of the Y.js server?

**Comment by dmonad** [comment]
Hi @echarles,

Yjs doesn't need a server implementation. You just need a mechanism to distribute updates. The y-websocket provider implements a server that distributes updates and persists them (you don't need to understand Yjs updates for that). Another use-case of the y-websocket server is to read Yjs documents (an compressed CRDT document in binary format) and store them in a readable format in an external database. For example, n seconds after each change you want to store the Jupyter document in clear-text form. You need to understand the Yjs document format for that.

I'm currently working on a Rust port of Yjs: [Yrs](https://github.com/yjs/yrs). We generate a WASM module from Yrs that can be included in all languages that understand wasm: [Ywasm](https://github.com/yjs/ywasm). Rust also has nice language bindings to many other languages like Python: [pyo3](https://github.com/PyO3/pyo3) & [wasmer-python](https://github.com/wasmerio/wasmer-python).

The goal is definitely to make Yjs available in more languages. Once Yrs is done we should be able to revise a Python port that includes all relevant features (reading document updates & converting Yjs document to a clear-text format).

I'm currently looking for funding to sponsor the development of Yrs. I'm looking for a sponsor or multiple sponsors who will allow me to focus on Yrs for three months. I'm happy to revise a Python port if that would be one of the conditions. There is a lot of interest in the Rust port, so I'm sure I will find sponsors eventually.

Things you could do right-away without Yrs:
* There is a C# port of Yjs that is fully featured: [Ycs](https://github.com/yjs/ycs) You could look into how well this can be ported to Python (using either native bindings or wasm-binding).
* You could run Node.JS in a container just to parse Yjs documents. Probably not the solution you were looking for, but it could be a solution until the Yrs/Ypython port is done.

**Comment by echarles** [comment]
> Yjs doesn't need a server implementation. You just need a mechanism to distribute updates. The y-websocket provider implements a server that distributes updates and persists them (you don't need to understand Yjs updates for that). Another use-case of the y-websocket server is to read Yjs documents (an compressed CRDT document in binary format) and store them in a readable format in an external database. For example, n seconds after each change you want to store the Jupyter document in clear-text form. You need to understand the Yjs document format for that.

I understand Y.js is architecture with providers https://github.com/yjs/yjs/blob/master/README.md#providers

As Jupyter needs to persist documents and receives cell execution requests, the ideal world is to extend our existing jupyter server (tornado based developed in python) with the CRDT handling.  Therefor the idea to have a CRDT extension developed in python that integrates nicely with the other services (content, kernel...). We also don't wait to add requirements like node.js, docker... to the users.  So having the same functionality as `y-websocket` in python would be great for us.

Another way would be to rely `y-webrtc` or `y-dat` to propagate the update to the clients. The server could be just another collaborator, but there again, we need python.

It is not clear to me what `y-indexeddb` is: are the update propagated or they just stay in the local browser?

> I'm currently working on a Rust port of Yjs: Yrs. We generate a WASM module from Yrs that can be included in all languages that understand wasm: Ywasm. Rust also has nice language bindings to many other languages like Python: pyo3 & wasmer-python.

Where is that WIIP repo? 

> The goal is definitely to make Yjs available in more languages. Once Yrs is done we should be able to revise a Python port that includes all relevant features (reading document updates & converting Yjs document to a clear-text format).

Have you already tried binding with Python? If such, I would be tempted to give it a try.

> I'm currently looking for funding to sponsor the development of Yrs. I'm looking for a sponsor or multiple sponsors who will allow me to focus on Yrs for three months. I'm happy to revise a Python port if that would be one of the conditions. There is a lot of interest in the Rust port, so I'm sure I will find sponsors eventually.

Good to know.

> Things you could do right-away without Yrs:
> There is a C# port of Yjs that is fully featured: Ycs You could look into how well this can be ported to Python (using either native bindings or wasm-binding).
> You could run Node.JS in a container just to parse Yjs documents. Probably not the solution you were looking for, but it could be a solution until the Yrs/Ypython port is done.

I am not sure C# will be easy to bind to Python. We have thought about the Docker option, but there a risk that the port woudl be delayed or would subperform.

**Comment by echarles** [comment]
Oh I see https://github.com/yjs/yrs

Is it too early to test? We have cycles to try that out with wasm bindings eventually. (cc/ @anirrudh)

**Comment by dmonad** [comment]
> It is not clear to me what y-indexeddb is: are the update propagated or they just stay in the local browser?

Yjs is a very modular project. The network providers sync data over networks (e.g. y-webrtc, y-dat, y-websocket). The database providers sync data to a database (e.g. y-indexeddb, y-leveldb, y-redis). Specifically the database providers listen to document updates on a Yjs document and then store them in a database. They may pull data from the database to stay in sync with the database even if another process is adding updates to the database (y-redis does that). y-indexeddb relies on a different network provider to communicate document updates to other clients (document updates stay in the browser). 

This was unclear to several users: You can use several providers at the same time. I clarify this in the new documentation website https://docs.yjs.dev.

> Have you already tried binding with Python? If such, I would be tempted to give it a try.

I have not. Sure, give it a shot! Yrs currently only supports insertions into a text document. It can sync with other clients using a binary document format (similar to the Yjs document format). There is an example folder that might be helpful to you: https://github.com/yjs/yrs/blob/main/examples/example.rs. Creating a JavaScript binding (using wasm-bindgen) was very straight forward and doesn't require a lot of Rust knowledge. I would be interested how well pyo3 works. Let me know if you have any questions.

To clarify the state of the Yrs port: I implemented the prototype to get a general feeling how a Rust port would look like and to estimate how long it would take me to write a complete port. The experience with Rust has been great. I also did some performance benchmarking that show that a Rust implementation can be much faster than Yjs because we have direct access to memory.

**Comment by anirrudh** [comment]
@dmonad this sounds great. @echarles thanks for the cc; I'll be taking a look at pyo3 and how to create a binding. What are your current plans with the Yrs port? Are you accepting PRs? I'll be checking it out more in depth tomorrow!

**Comment by dmonad** [comment]
Great @anirrudh Please let me know what you find out. 

I expect three more months of work on the Yrs port. I stopped development until I find a source of funding. This won't be a simple rewrite of Yjs. I want to implement more efficient data structures to handle CRDT structures. I did some preliminary work on designing these structures so I can benchmark the performance improvements.

I'm not sure how much sense it would make to accept PRs in this state. Depending on the use-case I surely will.

One of my main goals with Yrs is to improve adaptability to other languages. So your research is much-appreciated @anirrudh !

**Comment by anirrudh** [comment]
cc @pierrotsmnrd
