### ISSUE TITLE
Differential updates

### ISSUE THREAD

**Issue by dmonad** [yjs/yjs#263]
This is a ticket to track a new feature that will allow users to work with Yjs' document updates without loading the document to memory.

The state of the Yjs document, and also incremental modifications to the document are expressed as  "updates". The idea is now to allow clients to merge updates and compute the differences:

```js
// Instead of applying document updates to a Yjs update, you can simply merge updates:
currentState = Y.mergeUpdate([currentState, updateFromRemotePeer, someOtherUpdate])

// When syncing with another peer: Instead of loading the Yjs document to compute the differences, you can operate directly on the Yjs update:
const diffUpdate = Y.diffUpdate(currentState, remoteStateVector)

// We also need a method to encode the state vector directly from an update:
const stateVector = Y.encodeStateVectorFromUpdate(currentState)
```
The idea of the name `Y.diffUpdate` comes from set theory. I also like the name `Y.sliceUpdate`.

With this, it should be possible to modify the y-websocket server to not load the document to memory at all. Furthermore, we can implement more sophisticated providers that operate on document updates directly instead of the Y.Doc instance.

This is a WIP. I will post updates here.

**Comment by dmonad** [comment]
Short update: I extended the scope of the feature a bit.

Now you are able to merge updates, even if it would not be possible to construct a Yjs document update from it. For example, assume we start with an empty document and then a single client creates `update1`, `update2`, `update3`, and `update4`.

In Yjs, updates from a single user must arrive in creation-order. If we try to apply `update2` before `update1`, then we wait for `update1` to arrive before applying `update2`.

With the new implementation of the feature described above, we can merge updates in any order. I.e.

```js
const update24 = Y.mergeUpdates([update2, update4])
const update13 = Y.mergeUpdates([update1, update3])
const update1234 = Y.mergeUpdates(update24, update13)

equals(update1234, Y.mergeUpdates([update1, update2, update3, update4]))
```

The implementation of `Y.mergeUpdates` is now functional and very well tested on v1 encoding and v2 encoding.

Now I also want to allow gaps in Yjs. So a user should be able to apply `update2` before applying `update1`.

**Comment by bionicles** [comment]
could you please document a usage example for this in the readme, along with an example of the Redis backend? I'd love to play with it!

**Comment by dmonad** [comment]
Hi @bionicles , this will be super interesting for y-redis, but it still uses the old API. I documented the differential updates API with usage examples here: https://docs.yjs.dev/api/document-updates
