### ISSUE TITLE
Observer event doesn't include appropriate changes

### ISSUE THREAD

**Issue by Tpuljak** [yjs/yjs#264]
**Describe the bug**
Observing event on a Y object doesn't include appropriate changes. I believe the intended `event.changes` property should include `added, deleted, updated` properties but that doesn't seem to be the case. The `event.changes` appears to be undefined in my case preventing me from observing just the additions to an array for example.
This is the event object i get:
`{"target":[123],"currentTarget":[123],"transaction":{"doc":{"array":[123]},"deleteSet":{"clients":{}},"beforeState":{},"afterState":{},"changed":{},"changedParentTypes":{},"_mergeStructs":[],"origin":null,"meta":{},"local":true,"subdocsAdded":{},"subdocsRemoved":{},"subdocsLoaded":{}},"_changes":null,"_transaction":{"doc":{"array":[123]},"deleteSet":{"clients":{}},"beforeState":{},"afterState":{},"changed":{},"changedParentTypes":{},"_mergeStructs":[],"origin":null,"meta":{},"local":true,"subdocsAdded":{},"subdocsRemoved":{},"subdocsLoaded":{}}}`

I've created a [sample repo](https://github.com/Tpuljak/theia-yjs-example) (my intention is to use Yjs to achieve document syncing in the Theia editor).

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone the repo
2. `yarn && cd browser-app/ && yarn start /`
3. Run `PORT=1234 npx y-websocket-server` in another terminal instance.
4. Open 2 instances of the application (2 browser windows at http://localhost:3000)
5. In each of the instances run the command (from the command palette) 'Say hello' which instances the doc and provider.
6. In either of the windows run the command (from the command palette)  'Insert into Array'.
7. Check the console for the event object.

**Expected behaviour**
My expectation is that when an observe event is raised, the `event` object should contain an `added` property containing only added items to the array (or map).

**Environment Information**
 - Chrome 86
-  Node v12
 - `"yjs": "^13.4.4"`
-  `"y-websocket": "^1.3.6"`

**Comment by dmonad** [comment]
Hi @Tpuljak 

Happy to hear you started investing if that is feasible. 

`event.changes` is a computed property. So I think when you do `JSON.stringify(event)`, it won't print. You could try `JSON.stringify(event.changes)`.

This section could be interesting to you: https://docs.yjs.dev/api/shared-types/y.array

Please note that I'm still in the progress of describing the complete event system. For your scenario, you probably are only interested in `event.changes.delta`, which is basically a [Quill Delta](https://quilljs.com/docs/delta/) for Y.Array. It describes the changes that happened. 

If you are only interested in the items that were added, you could compute them from the delta. I'm also open to add an API to compute the added/removed items on the event object.

**Comment by dmonad** [comment]
FYI: I hope you also found this: https://github.com/yjs/y-monaco/

**Comment by Tpuljak** [comment]
Okay, it seems that was the problem but I'm still a little bit confused when it comes to the`event.changes.added` property.
This is the object I get when I print `event.changes`:
`{"added":{},"deleted":{},"delta":[{"insert":[123]}],"keys":{}}`

I assumed the [123] object I pushed would be in the `added` prop and not just in the delta. Thank you for the quick response.

P.S. I did find the y-monaco example and it has been a great help but I had to start from scratch basically to implement a more robust use case for a project I'm working on.

**Comment by dmonad** [comment]
`event.changes.added` is a [`Set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set). It doesn't convert to JSON. 

Specifically, it contains Yjs' `Item` instances that specify where content was added. Items have an API to calculate the relative position to other Items. This is important for me to compute the Delta.

> P.S. I did find the y-monaco example and it has been a great help but I had to start from scratch basically to implement a more robust use case for a project I'm working on.

Sure thing. That's what the examples are there for.
