### ISSUE TITLE
Y.Text applyDelta does not format multiple lines from a Quill.js delta

### ISSUE THREAD

**Issue by manstie** [yjs/yjs#271]
**Describe the bug**
A `Y.Text` instance does not format multiple lines when provided with a Quill.js delta which formats multiple lines.

**To Reproduce**
1. Apply a multi-line formatting quill delta to a `Y.Text` instance using `.applyDelta(delta.ops)`
e.g. 
```javascript
delta.ops = [
{ retain: 4, attributes: { bold: true }},
{ retain: 1 }, // newline character
{ retain: 10, attributes: { bold: true }},
{ retain: 1 }, // newline character
{ retain: 10, attributes: { bold: true }}
]
```

2. Read back the `Y.Text` delta using `.toDelta()`

3. See the delta returned only displays the first formatting operation
e.g.
```javascript
{ insert: 'Test', attributes: { bold: true }},
{ insert: '\nMulti-line\nFormatting' }
```

**Expected behavior**
The y-text should apply formatting to multiple lines at a time, given a quill delta which formats multiple lines.

**Screenshots**
See additional context

**Environment Information**
 - Browser: Chrome, Firefox
 - Yjs version: yjs@13.4.9, quill@1.3.7

**Additional context**
https://github.com/yjs/y-quill/issues/6

Easy copy-paste test:
```javascript
const testText = ydoc.getText('test');
testText.insert(0, 'Test\nMulti-line\nFormatting');
testText.applyDelta([
    { retain: 4, attributes: { bold: true }},
    { retain: 1 }, // newline character
    { retain: 10, attributes: { bold: true }},
    { retain: 1 }, // newline character
    { retain: 10, attributes: { bold: true }}
]);
console.log(testText.toDelta());
```

**Comment by dmonad** [comment]
Thanks for reporting such a detailed issue description. The issue is fixed in yjs@13.4.10.
