### ISSUE TITLE
Bloated npm bundle (4MB of docs)

### ISSUE THREAD

**Issue by gaberogan** [yjs/yjs#272]
**Is your feature request related to a problem? Please describe.**
The npm bundle is bloated with 4MB of docs. This is an easy fix that would half the size of the library.

**Describe the solution you'd like**
Remove docs from npm bundle

**Describe alternatives you've considered**
Module bundlers (snowpack, webpack, rollup) do a good job of shrinking the bundle down so this can be a work around in many cases.

**Comment by dmonad** [comment]
I think you are right about this. I cut down the size of the packed npm bundle to `290kb`. I think that should be fine for now..
