### ISSUE TITLE
Delta attributes only stop when there are other attributes or on a new line

### ISSUE THREAD

**Issue by boschDev** [yjs/yjs#277]
**Describe the bug**
When I apply some delta with some attributes the attributes will continue on the next insert. I saw that this is happening when you paste text in pm. It also occurs when the document will be fetched from the database. I was first debugging it in the yjs pm lib. After a while I found out that this issue is a bug in the yjs text class. The differences are better visible when putting 2 windows next to each other. The style is correct in the browser where you pasted content. In the other browser the delta attributes only stops when it encounters a new line or another attributes.

**To Reproduce**
Execute this code snippet. This is a striped version of what will be executed in the yjs pm lib. The actual place was the `createTypeFromTextNodes` function.
```javascript
const yDoc = new Y.Doc()
const text = yDoc.getText()
text.delete(0, text.length)
text.applyDelta([
  { insert: '123' },
  { insert: '123', attributes: { bold: true } },
  { insert: '123' }
])
console.log(text.toDelta())
```
See here the outcome

yjs 13.2.0
```json
[{"insert":"123"},{"insert":"123","attributes":{"bold":true}},{"insert":"123"}]
```

yjs 13.4.12
```json
[{"insert":"123"},{"insert":"123123","attributes":{"bold":true}}]
```

**Expected behavior**
I expect the outcome of yjs version 13.2.0 in the newer yjs versions.

**Screenshots**

**Environment Information**
 - Browser: Firefox 85 and Chrome 88
 - I checked all the versions from 13.2.0 to 13.4.12. The last time it was working for me was in version 13.2.0

**Comment by NickMitin** [comment]
@boschDev, hey!

I think we have same issue https://github.com/yjs/yjs/issues/275. We are investigating code at moment.

https://github.com/yjs/yjs/commit/186f7140b622aeda4b4a924dc9323513b2ca13c6 — this change is the result of such behaviour

**Comment by boschDev** [comment]
@NickMitin yes it seems the same issue (I missed issue #275). @dmonad I will close this issue of duplication of #275
