### ISSUE TITLE
QuillJS insertEmbed of image breaks the content and displays a weird behavior

### ISSUE THREAD

**Issue by sarahm7** [yjs/yjs#281]
**Describe the bug**
QuillJS insertEmbed of image breaks the YJS sync and displays a weird behavior. After embedding, a new line is created at the bottom of the editor, and when the user types on the bottom it duplicates the last 2 characters to the next line. Sometimes it also creates multiple empty new lines if you keep doing carriage returns on the bottom.

We are currently using the y-websockets-client to integrate with our existing endpoint for syncing the changes across. So far it works and we are only having issues with embedded images. Hope you can help us resolve this. 

I tried testing if we removed the "y.share.richtext.bindQuill(this.editor);" and the bug doesn't happen.

**To Reproduce**
1. Embed an image via the Quill toolbar, the issue is consistent if you embed 2-3 times
2. If the user restarts/reopens the editor, it works as expected again.
3. If multiple users embed at a time, changes are lost across sessions

**Screenshots**
![image](https://user-images.githubusercontent.com/27810542/110330336-9d54f480-8058-11eb-9a6f-a5a00041f7de.png)
![image](https://user-images.githubusercontent.com/27810542/110329527-aee9cc80-8057-11eb-8a5e-0ef18a8afddd.png)

**Environment Information**
 - Browser: Chrome
 - Node.js: 12.8.2
 - Angular: 7
 - Modules:
 "y-array": "10.1.4",
 "y-map": "10.1.3",
 "y-memory": "8.0.9",
 "y-richtext": "9.0.8",
 "y-websockets-client": "8.0.16",
 "yjs": "12.3.3",

HTML
`<quill-editor #editor [modules]="quillConfig" [theme]="theme" (keyup)="onKeyUp()" *ngIf="connected"
        (onEditorCreated)="onEditorCreated($event)" [preserveWhitespace]="true" [formats]="quillFormats"></quill-editor>`
 
TS:
       quillConfig: { [index: string]: Object } = {
            imageDropAndPaste: {
              handler: this.imageHandlerDragAndDrop.bind(this)
            },
            toolbar: [
              ['bold', 'italic', 'underline', 'image'],
            ],
            clipboard: {
              allowed: {
                tags: ['a', 'b', 'strong', 'u', 's', 'i', 'p', 'br', 'ul', 'ol', 'li', 'span'],
                attributes: ['href', 'rel', 'target', 'class']
              },
              keepSelection: true,
              matchVisual: false
            }
        }; 

     imageHandlerToolbar(): void {
            ------ upload and generate URL ----
            this.insertToEditor(url);
     }

     insertToEditor(url: string): void {
          const addImageRange: QuillNamespace.RangeStatic = this.editor.getSelection();
          const newRange: number = addImageRange !== null ? addImageRange.index : 0;
          this.editor.insertEmbed(newRange, 'image', url, 'api');
          this.editor.insertText(newRange + 1, ' ', 'api');
          this.onKeyUp();
          this.uploadingImage = false;
      }

     onEditorCreated(editor: QuillEditor): void {
            this.editor.getModule('toolbar').addHandler('image', () => {
              this.imageHandlerToolbar();
            }); 
            this.socket = io(environment.liveEditHubUrl, { transports: ['websocket'] });
        
            // pass the dependency of yjs
            Y.extend(yArray, yMemory, yWebsocketsClient, yMap, yRichText);
            // initialize y instance.
            // Returns promise with Y instance;
            Y({
              db: {
                name: 'memory'
              },
              connector: {
                name: 'websockets-client',
                room: this.subNote.id.toString(),
                socket: this.socket,
                url: environment.liveEditHubUrl
              },
              share: {
                richtext: 'Richtext'
              }
            }).then((y: Y) => {
              this.yService = y;
              y.share.richtext.bindQuill(this.editor);
              this.editor.setSelection(this.editor.getLength() - 1, this.editor.getLength());
              this.connected = true;
            }).catch(() => {
              this.connected = false;
            });
     }

**Comment by dmonad** [comment]
Hi @sarahm7 , I don't provide community support for Yjs v12 anymore. We are running v13 for over a year now - a complete rewrite. Supporting old versions for non-paying users is infeasible at this point. However, I'm happy to accept a PR to fix the issue (you can create a branch using the latest v12 version).

**Comment by sarahm7** [comment]
hi @dmonad , that's unfortunate. I can't migrate to v13 as the WebSocket implementation is a bit different from the v12 - which worked perfectly for us (please do correct me if I'm wrong). Is there any way you can confirm it's not caused by my implementation? I'll be trying to check as well if it really is a bug on the v12 version as well.

**Comment by dmonad** [comment]
I would have to look at your codebase to confirm. But this issue checks out. This looks like an issue with the newline implementation "bug" in Quill. Quill didn't emit changes for the last newline character in Quill. Often, when a new paragraph/embed is inserted at the end of a document, this might lead to inconsistencies. This is now fixed. I remember that y-richtext worked fine with some specific versions of Quill (so you might fix the issue by downgrading to an older version of Quill - the one that was used when this package was last updated would be a good start).
