### ISSUE TITLE
Bundle is incompatible with browsers

### ISSUE THREAD

**Issue by nin-jin** [yjs/yjs#282]
I try to use yjs from CDN in [benchmark](https://perf.js.hyoo.ru/#prefix/prefixes=%5B%22const%20%7B%20Doc%20%7D%20%3D%20%24mol_import.module%28'https%3A%2F%2Funpkg.com%2Fyjs%4013.5.1%2Fdist%2Fyjs.mjs'%29%5Cnconst%20ydoc%20%3D%20new%20Doc%28%29%5Cnconst%20val%20%3D%20ydoc.getArray%28'count'%29%22%2C%22%24mol_import.script%28'https%3A%2F%2Funpkg.com%2Fautomerge%400.14.2%2Fdist%2Fautomerge.js'%29%5Cnlet%20val%20%3D%20Automerge.from%28%7B%20val%3A%20%5B%5D%20%7D%29%22%2C%22%22%5D/sources=%5B%22val.push%28String%28%7B%23%7D%29%29%5Cnval.pop%28%29%22%2C%22val%20%3D%20Automerge.change%28val%2C%20'Ins'%2C%20doc%20%3D%3E%20%7B%5Cn%20%20doc.val.push%28String%28%7B%23%7D%29%29%5Cn%7D%29%5Cnval%20%3D%20Automerge.change%28val%2C%20'Ins'%2C%20doc%20%3D%3E%20%7B%5Cn%20%20doc.val.pop%28%29%5Cn%7D%29%22%5D) but can't:

```
import( 'https://unpkg.com/yjs@13.5.1/dist/yjs.mjs' )
import('https://unpkg.com/yjs@13.5.1/src/index.js')
```

![](https://i.imgur.com/vnPg5el.png)

Could you fix it or provide standalone bundle as other libraries?

**Comment by nin-jin** [comment]
I try to use other cdn and it helps. [Results.](https://perf.js.hyoo.ru/#prefixes=%5B%22%24mol_import.script%28'https%3A%2F%2Funpkg.com%2Fhyoo_crowd_lib%401.0.2%2Fweb.js'%29%5Cnlet%20list%3D%20%24hyoo_crowd_list.make%28%29%22%2C%22%24mol_import.script%28'https%3A%2F%2Funpkg.com%2Fautomerge%400.14.2%2Fdist%2Fautomerge.js'%29%5Cnlet%20doc%20%3D%20Automerge.from%28%7B%20list%3A%20%5B%5D%20%7D%29%22%2C%22const%20%7B%20Doc%20%7D%20%3D%20%24mol_import.module%28'https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fyjs%2F%2Besm'%29%5Cnconst%20doc%20%3D%20new%20Doc%5Cnconst%20list%20%3D%20doc.getArray%28%20'list'%20%29%22%5D/sources=%5B%22%7B%5Cn%5Ctlist.insert%28%7B%23%7D%29%5Cn%5Ctif%28%20%7B%23%7D%20%3E%20max_count%20%29%20list.cut%28%20list.items%5B0%5D%20%29%5Cn%7D%22%2C%22doc%20%3D%20Automerge.change%28%20doc%2C%20'op'%2C%20doc%20%3D%3E%20%7B%5Cn%5Ctdoc.list.push%28%7B%23%7D%29%5Cn%5Ctif%28%20%7B%23%7D%20%3E%20max_count%20%29%20doc.list.shift%28%29%5Cn%7D%20%29%22%2C%22list.push%28%5B%7B%23%7D%5D%29%5Cnif%28%20%7B%23%7D%20%3E%20max_count%20%29%20list.delete%280%2C1%29%22%5D/prefix=const%20max_count%20%3D%20100)

**Comment by disarticulate** [comment]
I believe i got a umd module working here:

https://github.com/disarticulate/yjs/blob/main/rollup.config.js

```
{
  input: './src/index.js',
  output: {
    name: 'Y',
    file: 'dist/yjs.min.js',
    format: 'umd',
    sourcemap: false
  },
  plugins: [
    nodeResolve({
      mainFields: ['module', 'main']
    }),
    commonjs(),
    terser()
  ]
}
```

https://github.com/disarticulate/yjs/blob/main/rollup.config.js

**Comment by dmonad** [comment]
Yjs is a pure EcmaScript module. They are well adapted in modern JavaScript bundlers. Even CDNs tend to support them natively now. Other libraries only expose a single functionality. Yjs has an ecosystem of extensions that all share functionality that is implemented in lib0. I can't really publish all features as one big bundle because it would be too big.

I recommend unpkg as a CDN (if you have to). You just need to append a flag like so: `import('https://unpkg.com/yjs?module')`

**Comment by nin-jin** [comment]
[It's works too.](https://perf.js.hyoo.ru/#prefix=const%20max_count%20%3D%20100/prefixes=%5B%22const%20%7B%20Doc%20%7D%20%3D%20%24mol_import.module%28'https%3A%2F%2Funpkg.com%2Fyjs%4013.5.1%2Fdist%2Fyjs.mjs%3Fmodule'%29%5Cnconst%20doc%20%3D%20new%20Doc%5Cnconst%20list%20%3D%20doc.getArray%28%20'list'%20%29%22%2C%22%22%2C%22%22%5D/sources=%5B%22list.push%28%5B%7B%23%7D%5D%29%5Cnif%28%20%7B%23%7D%20%3E%20max_count%20%29%5Cn%5Ctlist.delete%280%2C1%29%22%5D)
