### ISSUE TITLE
Performance: initialization of the large document is much faster in Safari than in Сhrome and FF

### ISSUE THREAD

**Issue by zarv1k** [yjs/yjs#283]
**Describe the bug**
Applying the same large initial document update ([~6MB](https://www.dropbox.com/s/2idjt8qdwujzsik/large-y-doc.bin?dl=0)) takes different time in different browsers, the worst performance is in Chrome (about ~90 times slower than in Safari). Please take a look:

**Safari** ~1s:
applyUpdate byteLength=5.747MB: 809.174ms

**FF** from ~3-40s:
applyUpdate byteLength=5.747MB: 40792ms

**Chrome** ~88s:
applyUpdate byteLength=5.747MB: 87892.05786132812 ms

It seems that the function `tryToMergeWithLeft` (slow in Chrome) is called quite often by `tryMergeDeleteSet` and the main bottleneck might be there. Unfortunately I can't understand why it's much faster in Safari.

**To Reproduce**

```ts
const logLabel = `applyUpdate byteLength=${(initialUpdateFromDB.byteLength / 1024 / 1024).toFixed(3)}MB`;
console.time(logLabel);
const yDoc = new Y.Doc();
Y.applyUpdate(yDoc, initialUpdateFromDB);
console.timeEnd(logLabel);
```
**Expected behavior**
Initial applyUpdate in Chrome & FF as fast as in Safari.

**Screenshots**

<img width="902" alt="Screen Shot 2021-03-12 at 15 13 38" src="https://user-images.githubusercontent.com/6296643/110943253-0f288900-834c-11eb-9931-5ede3bb5d78b.png">

**Environment Information**
 - Chrome 89.0.4389.82, Firefox 86.0.1, Safari 14.0.2
 - yjs v13.5.1.

**Additional context**
Interesting fact, that sequential initializations of the exactly same initial update could lead to completely different results only in FF, randomly from quite fast (~3s) to slow (~40s).

**Comment by dmonad** [comment]
Hi @zarv1k ,

thanks for sharing this! Is this a real-world dataset or did you somehow construct it?

I mainly optimize for Chrome/Node/V8, so I'm surprised that Safari is so much ahead.

Yjs relies on the compiler to optimize code. The "hot path" should be heavily optimized, but sometimes the runtime engine doesn't make the right decision and doesn't optimize functions that are often called. For some reason, the function `tryMergeDeleteSet` is not optimized which leads to performance problems in your case. The runtime engine optimizes functions that, based on the current information, are worth optimizing. This process is really non-deterministic. However, when you run the same benchmark multiple times, you might get more consistent results.

Another reason why `tryMergeDeleteSet` could take so long is that the garbage collector is called while this function is active.

Examples like yours are very useful to optimize Yjs. If you find a way to run your example with more consistent performance, then Yjs' overall performance will likely increase.

In nodejs, you can trace performance optimizations and deoptimizations: 
`node --trace-deop bench.js` and `node --trace-opt bench.js`. This might lead to some more insight into why the function doesn't perform well.

**Comment by zarv1k** [comment]
@dmonad I'm developing some collaborative painting tool via yjs, this example is a result of adding some figures by hand + a lot of undo/redo operations with them, so although it was made during debugging the sync via Yjs I think real users would behave like that in production :)

I caught slow native `Array.splice()` in Chrome using a bit [smaller initial doc]() (~0.849MB).  Here is [chrome performance json profile file](https://www.dropbox.com/s/bamjtuwmilatjfx/smaller-y-doc-slow-profile.json?dl=0).

**Chrome**:
applyUpdate byteLength=0.810MB: 4250.22216796875 ms

**Safari**:
applyUpdate byteLength=0.810MB: 110.296ms


<img width="1111" alt="Screen Shot 2021-03-12 at 17 40 36" src="https://user-images.githubusercontent.com/6296643/110955342-8d8c2780-835a-11eb-8917-f908433a567b.png">

**Comment by zarv1k** [comment]
@dmonad, I just noticed one interesting thing: Yjs document updates mentioned in comments of this issue are produced on the server-side where I use differential updates only (w/o loading Y.Doc instance). On the client side I checked the size of the full update just after applying the server-side initial update to the Y.Doc instance and the produced update is surprisingly much smaller in size:

```ts
const logLabel = `applyUpdate byteLength=${(initialUpdateFromDB.byteLength / 1024 / 1024).toFixed(3)}MB`;
console.time(logLabel);
const yDoc = new Y.Doc();
Y.applyUpdate(yDoc, initialUpdateFromDB);
console.timeEnd(logLabel);

console.log('before', initialUpdateFromDB.byteLength, 'after', Y.encodeStateAsUpdate(yDoc).byteLength);
```

**NodeJS**:

[large update](https://www.dropbox.com/s/2idjt8qdwujzsik/large-y-doc.bin?dl=0)
applyUpdate byteLength=5.747MB: 4228ms
before 6026596 after 452155

[smaller update](https://www.dropbox.com/s/vq4lp1ko81rei87/smaller-y-doc-slow.bin?dl=0)
applyUpdate byteLength=0.810MB: 469ms
before 849136 after 75644

It seems that the merged update which is created w/o loading Y.Doc instance by only merging differential updates is much bigger in size and it can lead to such performance issues on the client side during the document initialization.

I don't really into the internals of Yjs, so I can't say if it is OK or not. Any ideas? Anyway, how can I reduce the size of the result update on the server-side w/o loading Y.Doc instance?

Thank you.

**Comment by dmonad** [comment]
That makes sense. This also explains why `tryToMergeWithLeft` takes up so much time. 

The differential updates feature doesn't garbage-collect deleted content. The garbage-collector is an optional feature and is currently only implemented in Y.Doc. I'm sorry that I didn't make this clear in the documentation. I updated the documentation just now.

So when you load a document to a `Y.Doc` with enabled garbage-collector, you perform the cleanup on all deleted operations at once. Usually, you do this over several sessions. This can certainly be optimized. My recommendation, for now, is to you load the document to a Y.Doc from time to time (e.g. every day or at the end of every session) to perform the cleanup.

**Comment by zarv1k** [comment]
Thanks a lot for your explanation, seems to be clear for now and I'll try to implement gc strategy on backend side that way you suggested.

I'm closing the issue for now. Please feel free to reopen it, if you think such performance differences should be investigated more deeply.

**Comment by georeith** [comment]
+1 am seeing this in the `y-indexeddb` adapter. I am able to load large documents from my server because I am using `encodeStateAsUpdate` with differential state vectors.

Loading from indexeddb however freezes and ultimately crashes because of `tryMergeDeleteSet` at the end of the transaction.

**Comment by georeith** [comment]
I am also building collaborative design software (vector). This happens when a user selects a large number of elements and moves them around (generates a lot of changes to the document which creates a large amount to garbage collect).
