### ISSUE TITLE
Empty event on initial sync

### ISSUE THREAD

**Issue by YousefED** [yjs/yjs#293]
Trying to completely grasp Yjs events (and figuring out a robust pattern to load initial data).

Sandbox: https://codesandbox.io/s/pensive-jones-4fhkf?file=/src/index.ts

To open a client:
1. Click "open in new window" in top right
2. Append a query string (e.g.: `?test`) to the url. For debugging purposes the code doesn't do anything otherwise

My observations:
1. Opening 1 client (client A). I see 1 "added" event, which makes sense
2. Opening 2nd client (client B). I see 1 "added" event, and one "update" event. Even though the value is the same for both events, this kind of makes sense as the second value comes from client A.
3. However, client A also has an extra event now. This is unexpected, I would expect that client As state would be the "truth" that's subsequently synced to client B. It's also suspicious that this event is completely "empty":
![image](https://user-images.githubusercontent.com/368857/114664975-be1a0500-9cfc-11eb-8197-a02c3d1d7972.png)

Can you explain the extra event, or is this a bug? As a developer, for me it's unexpected to get any "empty" events like this.

(What I suppose might be happening; the data from Client B is also synced to Client A, so that both clients have the same "history". It's confusing this would raise an empty event though.)

**Comment by dmonad** [comment]
Every time you open the website, you will create a new Y.Text object on `ymap = ydoc.getMap('')`.

Since you create key-value entry on `ymap` before receiving the initial content from other clients, you will always overwrite Y.Text. ` if (!text) {` is aways executed. 

Then it depends on chance. Either the new Y.Text will create a new insertion or it will be ignored (because it is a concurrent insertion).

Instead of `ydoc.getMap('')` you could maybe do `ytext = ydoc.getText('')` to create a Y.Text directly.

**Comment by dmonad** [comment]
Also, an empty event is not a bug. In some cases, you want to get an event when another user "tried" to overwrite something but didn't succeed because a concurrent change was prioritized.

**Comment by dmonad** [comment]
Generally, you might get events whenever a change was applied to a shared type. Even if that change was immediately overwritten and doesn't lead to any changes that can be expressed in `event.changes`.

**Comment by YousefED** [comment]
Thanks for the explanation. I was using Maps to organize the document, but I suppose I can define more elements on the "root" like you suggested (`ydoc.getText('')`).

Now how would I go about this for subdocs? Because as far as I understand, subdocs cannot be defined on the root (i.e.: there is no `ydoc.getSubDoc()`. Or can I use `this.ydoc.get("sub", Y.Doc);`?

> Also, an empty event is not a bug. In some cases, you want to get an event when another user "tried" to overwrite something but didn't succeed because a concurrent change was prioritized.

Got it, thanks. As a consumer of the library it would then still be useful to be able to inspect the "reason" of the event, so I can ignore it if it's a "failed-overwrite".

**Comment by YousefED** [comment]
Also, how would I initialize the text with "hello"? If I'd use `.insert(0, "hello")`, I suppose I'll get "hellohello" when two clients connect?

**Comment by dmonad** [comment]
@YousefED 

Regarding the initial content, you can have a look at https://discuss.yjs.dev/t/initial-offline-value-of-a-shared-document/465

> Now how would I go about this for subdocs? Because as far as I understand, subdocs cannot be defined on the root (i.e.: there is no ydoc.getSubDoc(). Or can I use this.ydoc.get("sub", Y.Doc);?

Subdocus are meant for creating nested structures. This feature is for enabling users to embed Yjs documents into other types. so `ydoc.getSubDoc` is not possible. Instead, you could simply create another document. 

> Got it, thanks. As a consumer of the library it would then still be useful to be able to inspect the "reason" of the event, so I can ignore it if it's a "failed-overwrite".

Thanks. I will keep that in mind. Maybe in the next version.

**Comment by YousefED** [comment]
Ok, thanks for the explanation. As this is not a bug I'll continue the discussion on the forum!
