### ISSUE TITLE
Y.Array has incorrect contents and length when deleting and inserting multiple times in a single transaction

### ISSUE THREAD

**Issue by georeith** [yjs/yjs#297]
**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**

`Y.Array` returns an incorrect length and has wrong contents after multiple deletions and insertions have occured in a single transaction.

**To Reproduce**

I have made a small reproduction here. You can see the array logs out as having a length of `3` but contains `5` members 
https://codesandbox.io/s/wizardly-stonebraker-idnnx?file=/src/index.js

**Expected behavior**
The `Y.Array` should have a length of `4` and contain `4` members. (You can see this is the case if you remove the `doc.transact()`)

**Screenshots**

**Environment Information**
 - Browser
 - Yjs version: 13.5.5

**Comment by georeith** [comment]
I have noted that YJS version 13.2.0 does not have the issue: https://codesandbox.io/s/fast-currying-2mez6?file=/src/index.js but 13.3.0 does.

**Comment by dmonad** [comment]
I'm really happy that you found this issue. The sandbox was very helpful. Thanks so much for reporting it! 

I fixed it in yjs@13.5.7.
