### ISSUE TITLE
missing attribute when deleting the whole content using applyDelta

### ISSUE THREAD

**Issue by calibr** [yjs/yjs#305]
**Describe the bug**

When the whole formatted content gets deleted from YText using applyDelta and then new content gets inserted in the same call with the same attribute, this attribute will be missed from the resulting content.

**To Reproduce**

```
const yjs = require('yjs')

const doc = new yjs.Doc()
const text = doc.get('text', yjs.Text)
const str = 'hello world'

text.applyDelta([{
    insert: str,
    attributes: {
      bold: true
    }
}])

text.applyDelta([
  { delete: str.length },
  {
    insert: 'hello',
    attributes: {
      bold: true
    }
  }
])

console.log(text.toDelta())
```

This code prints:
```
[ { insert: 'hello' } ]
```

**Expected behavior**

Result of the code above should be:
```
[ { insert: 'hello', attributes: {bold: true} } ]
```

**Environment Information**

Yjs 13.5.8

**Additional context**

On the line https://github.com/yjs/yjs/blob/main/src/types/YText.js#L469
if i replace `map.copy(currPos.currentAttributes)` to just `currPos.currentAttributes` it seems to be working fine, but I am hesitating because it may break something else.

**Comment by dmonad** [comment]
I'm sorry for taking such a long time for fixing this issue. 

You are right, copying the map will probably lead to other problems. I fixed the edge case and I will publish a fix in a bit.
