### ISSUE TITLE
Undo/Redo corrupts nested data

### ISSUE THREAD

**Issue by georeith** [yjs/yjs#317]
> Please save me some time and use the following template. In 90% of all issues I can't reproduce the problem because I don't know what exactly you are doing, in which environment, or which y-* version is responsible. Just use the following template even if you think the problem is obvious.

**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**

Undo/Redo corrupts nested data. There is a reproduction below that shows it simply.

**To Reproduce**

I have made a reproduction here.
https://codesandbox.io/s/hardcore-jang-kkoho?file=/src/index.js

You can see that the final output is: 

```
{"text":{}}
```

A state that never existed. When it should be:

```
{"text":{"blocks":{"text":"Something Else"}}}
```

**Expected behavior**
Undo/Redo should not corrupt data

**Environment Information**
 - Browser: Chrome 91
 - Yjs: 13.5.11

**Comment by zarv1k** [comment]
@dmonad, would you have any time to check this issue out and to have this issue fixed in nearest future? Please, it would be really awesome.
