### ISSUE TITLE
Attributes are not applied to YXmlTexts

### ISSUE THREAD

**Issue by vivaxy** [yjs/yjs#319]
**Checklist**

* This is a bug.
* And a bug in yjs.

**Describe the bug**

Applying deltas with attributes, some attributes are missing.

```js
xmlText.applyDelta([
  { insert: "A", attributes: { em: {}, strong: {} } },
  { insert: "B", attributes: { em: {} } },
  { insert: "C", attributes: { em: {}, strong: {} } }
]);
```

**To Reproduce**
[CodeSandbox link](https://codesandbox.io/s/sleepy-golick-s0ol6?file=/src/index.js) to reproduce the issue.

Open Console to see the output as `<em><strong>A</strong></em>B<strong>C</strong>`

**Expected behavior**
Expected to have texts as `<em><strong>A</strong></em><em>B</em><em><strong>C</strong></em>`

**Screenshot**
![image](https://user-images.githubusercontent.com/4216856/126961315-3e4e7fa2-ffd2-4cfe-b36f-1e1ecf3bd589.png)

**Environment Information**
 - Browser and Node.js.
 - Yjs@13.5.11

**Comment by dmonad** [comment]
Hi @vivaxy,

thank you for reporting this bug and especially for providing a fix!

The fix really helped me to debug this issue quickly. Another problem is that the `currPos` attribute is not correctly updated. This could potentially lead to other bugs. In any case, I'm really happy that this is now fixed.
