### ISSUE TITLE
Max name length for shared type?

### ISSUE THREAD

**Issue by IDlOT** [yjs/yjs#322]
Hello! I'm trying to use y-websocket to share many Richtext documents over one y-websocket server. I'm trying to supply a 32-character uuid as the name for the type, i.e. `const type = doc.getText(uuid)`. First of all, if there is a better way of going about this, please point me in the right direction! All of these documents will be initially loaded from and ultimately saved to a database.

Anyway this causes what appears to be an infinite loop, with anything typed being duplicated in increasing amounts. Upon reload the document is full of endless duplicate characters and crashes. This happens when there is only one client connected, or two. I've tested with other long, hard-coded strings as the type name with the same result. Short, random strings however work just fine.

**Expected behavior**
Successfully create shared type with a long string name.

**Environment Information**
 - Chrome, Node.js, Next.js, React
 - Yjs v13.5.11, y-websocket v1.3.16, y-quill v0.1.4

**Comment by IDlOT** [comment]
Update: I'm starting to think there's more to this problem than just string length. It's failing with short names as well. Two followup Q's:

1. Are there only certain names we can use for these types?
2. Are there any special considerations to be taken into account for Next.js hot reloading, besides just dynamically importing react-quill? The duplicate characters/crashing seems to occur off of a hot reload.

Thanks for any and all help.

**Comment by dmonad** [comment]
Hi Tammer,

You can create shared types with any length (the max size of any string in Yjs is about 2^32 (so it's pretty damn large). The problem you are experiencing is probably another one.

You - and this is just an assumption - probably try to initialize the same shared type every time to create it. Something like 

```js
ytext.insert(0, '...')
```

This means that every client will insert content. You should only initialize once. Also this seems curious:

```js
doc.getText(uuid)
```

Usually, you would give the document a uuid, not the name of the type. Once you create a shared type on one peer, you will sync that to all peers that are connected.

There is a nice tutorial for managing documents here: https://docs.yjs.dev/getting-started/a-collaborative-editor
Use your UUID as the "room name".

I'm closing this ticket. In the future please use discuss.yjs.dev for questions. This is just for bug reports.
