### ISSUE TITLE
Docs: Misleading reference to Lamport Timestamp

### ISSUE THREAD

**Issue by burdiyan** [yjs/yjs#324]
This is not strictly a bug, although I couldn't find a better place to report this.

INTERNALS and README files in this repo mention that YJS uses Lamport Timestamps for the clock part of the ID of items. I find it a bit misleading, because Lamport Timestamps implies that timestamps convey happened-before relation of events across "processes". In YJS clock is monotonically increasing within the single "process", and there's no relation between clock values across processes, i.e. each process increments its own logical clock.

I guess YJS clocks can still be called logical clocks, but not exactly Lamport one.

**Comment by dmonad** [comment]
Hi @burdiyan,

The item ID - i.e. the combination of client and clock - is the textbook definition of a Lamport Timestamp. Terms often change, but a Lamport Timestamp is always made up of a logical, ever-increasing clock and a client-id that identifies the process. 

Cheers,
Kevin

**Comment by burdiyan** [comment]
I think I can't agree with that. This topic is probably a place for a holy war, but I don't want to start one :)

Only to say that knowing about Lamport Clocks from other contexts (distributed systems, but outside the scope of CRDT), it was confusing for me to find out that YJS clocks are not "shared" among peers.

I'm not sure about "textbook definition" for Lamport Timestamps, but if I'm not mistaken the Lamport's paper "Time, Clocks, and the Ordering of Events in a Distributed System" was the first one introducing the concept. And this paper clearly speaks about the importance of conveying the happened-before relation among processes, not so much (if at all) about the fact that you can make a unique ID by combining client and clock.

But you're right that terms often change, so probably all of this is debatable, and subject to interpretations.

It's good that this discussion will at least stay recorded here for any future people wondering about that.

**Comment by dmonad** [comment]
Leslie Lamport was the first person to describe the idea to maintain logical clocks *for each process* to describe happened-before relations. The paper is not very accessible. The Wikipedia article is easier to read and gives practical examples. 

> A Lamport logical clock is a numerical software counter value maintained in each process. [(source)](https://en.wikipedia.org/wiki/Lamport_timestamp)

The combination of `(client, clock)` represents a Lamport Timestamp. `(client, clock)` also happens to be a unique id. Here, the client represents a process. Each client has an ever-increasing clock that is updated when a new operation is created. This makes it possible to describe happened-before relations on operations. E.g. `(0, 1)` happened before `(0, 3)`. An operation could further describe that a certain operation must be executed after another. E.g. `{ action: "ring bell", id: (0, 0) }` and `{action: "open door", id: (1, 0), after: (0, 0)}` (only open the door after the bell rang). The possibilities of lamport timestamps are infinite. You can do all sorts of things with them. A popular extension is to use them to create state vectors. 

> But you're right that terms often change, so probably all of this is debatable, and subject to interpretations.

I meant that other projects often use different terminology. They might use different names like `(process, time)` or `(actor, counter)` to make up a lamport timestamp. You could use actual time for Lamport timestamps as well, as long as a timestamp is maintained for each process. But the idea is always the same. Each process has an ever-increasing logical clock. Yjs is not unique here. All list-based CRDTs that I know use this concept.
