### ISSUE TITLE
Is there a way to use yjs without webpack? (in the browser, obv.)

### ISSUE THREAD

**Issue by almosnow** [yjs/yjs#325]
I would like to have a single (or multiple) minified script that I just add on my html's head like any other JS library out there.

Wondering if this is possible in the current version of yjs.

**Comment by almosnow** [comment]
Closed w/ no comments? Whoa, what a dick.

**Comment by dmonad** [comment]
> Closed w/ no comments? Whoa, what a dick.

1. You ignored the guidelines. 2. This question has been answered multiple times. 

I answer questions for free because I want to help people. I expect you to help me be efficient. If you don't contribute by at least following the guidelines or researching if this question has been answered before, you don't get an answer. Another comment like this and you get banned.

**Comment by almosnow** [comment]
>or researching if this question has been answered before
Nope, it hasn't (i.e. it doesn't have a solution).

Sorry about cursing, that was unwarranted, I was having a shitty day but I can do much better.

Please consider that some people do not (want to) jump into the "modern developer toolset" bandwagon. IMO, you just can't beat the deployment speed of a <script ...> tag.

Anyway, if anyone else comes around, I solved it like this:

1. Install webpack (obv.)
2. Create a script with the following contents:
(I named mine `yjs.13.5.12.js`)
```
import * as YJS from 'yjs';

self.YJS = YJS;
```

3. Run webpack like `webpack --entry ./yjs.13.5.12.js`

And voila, you'll have a minified YJS inside `dist/` on your path.

To use, just add the script as usual and you should have YJS on your running context.

>I answer questions for free because I want to help people.
YJS is awesome and I truly appreciate that you're giving it for free. I am doing this as a prototype for a client now, so if they give us a green light I'll make sure some of the revenue goes back to support your work.

Thanks and Best!

**Comment by dmonad** [comment]
Another approach is described here: https://github.com/yjs/yjs/issues/282
