### ISSUE TITLE
ydoc.destroy() and provider.destroy() not clearing yjs document from memory

### ISSUE THREAD

**Issue by BennettBallowePF** [yjs/yjs#330]
Calling ydoc.destroy() along with provider.destroy doesn't seem to clear the document from memory.  While using the yjs-demos quill demo along with a local y-websocket server I added a button which triggers the destroy code below. When I refresh the page or close and open it in another browser I can see the data in the quill editor is still persisting. 

```
const destroyBtn = document.getElementById('destroy-ydoc')
  destroyBtn.addEventListener('click', () => {
	ydoc.destroy();
  })
  
  ydoc.on('destroy', update => {     
	 provider.destroy();
	 console.log('ydoc and provider destroyed') 
    })
```
 

**To Reproduce**
1. Add the following button to the quill demo html page `<button id="destroy-ydoc">destroy the YDoc</button>`
2. Add the following code to the quill.js file in the quill demo:
```
const destroyBtn = document.getElementById('destroy-ydoc')
  destroyBtn.addEventListener('click', () => {
	ydoc.destroy();
  })
  
  ydoc.on('destroy', update => {
	 provider.destroy();
	 console.log('ydoc and provider destroyed')
    })
```
3. Run the quill demo with a local y-websocket server, type something into the quill editor, hit the destroy button, refresh the page or open the page in another browser and see that the quill text still persists. I would think that if the document is destroyed no data would exist in memory, therefore the quill editor would be blank. If I restart my local node server, the document will be blank as expected.

**Environment Information**
browser: latest version of chrome or firefox
yjs version: latest code in the yjs-demos and y-websocket repos (yjs@13.5.6)
node version: v12.4.0
npm version: 6.9.0

**Comment by philipaarseth** [comment]
Any updates on this? seems .destroy() does nothing and just returns the same document

**Comment by dmonad** [comment]
Hi @philipaarseth,

The destroy method merely unregisters all event handlers and cleans up subdocuments. It is recommended that you call this method when you don't need it anymore.
