### ISSUE TITLE
Undo/Redo corrupts nested data 2

### ISSUE THREAD

**Issue by georeith** [yjs/yjs#343]
**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**

This is a continuation of https://github.com/yjs/yjs/issues/317

While the example in that issue was solved unfortunately the issue still persists and I made another reproduction here:

https://codesandbox.io/s/hardcore-jang-kkoho?file=/src/index.js

The original issue looked at undoing 2 changes, that was fixed. However 3 or more changes produces the same issue still.

**To Reproduce**

See above

**Expected behavior**

Data not to corrupt

**Environment Information**
 - Yjs version: 13.5.16

**Comment by chanced** [comment]
It seems prepending that undo/redo chain with a redo first keeps the data intact.

https://codesandbox.io/s/sparkling-sea-sf6sk

**Comment by dmonad** [comment]
I fixed this in the latest release. The fix seems to be working, but let me know if there are more issues.
