### ISSUE TITLE
When first ytext1 updates a sparse attribute for a range by text.format, second ytext2 observer triggered twice and sent the second set of delta back to ytext1 

### ISSUE THREAD

**Issue by btezzxxt** [yjs/yjs#344]
**Describe the bug**
example here https://codesandbox.io/s/yjs-test-txi-ucwmy?file=/src/index.ts, deltas are printed out in the console
1.init a doc/ytext with a '\n' at index 0, attributes `{LIST_STYLES: "bullet"} `and a 'abc' at indices 1-3 with empty attributes. LIST_STYLES is a sparse attribute that not every delta has. 
2.Then doc1 does `text1.format(0, 1, { LIST_STYLES: "number" });`
observer1 successfully received one delta `{retain1: 1, attributes: {LIST_STYLES: number}}`
3.however 'remote' observer2 got triggered twice - first time with the same delta `{retain1: 1, attributes: {LIST_STYLES: number}}`. second time, it got another set of deltas [{retain: 1}, {retain: 3, attributes: {LIST_STYLES: null}]
4.observer1 received the second set of deltas too
5.it seems that when doc2 applied the change from doc1, it generated another change then applied to itself, then that triggers a change back to doc1, and that seem to be a round trip

my guess for above is that since LIST_STYLES is a sparse attribute that's not on text 'abc' so doc2 generated `{retain: 3, attributes: {LIST_STYLES: null}` itself. This extra change doesn't seem to affect the actual doc state but took an extra trip. On our app side, we had to take extra verification and ignore the second delta as LIST_STYLE 's supposed to work from indices 0-3.

Would like to learn the use case of need for Yjs for this null setting delta; if not, could we have a fix for it so on the app side we don't have to make the extra validation or the extra message sending between clients. Thanks!

**Expected behavior**
would prefer that when doc2 applies the update, it should not generate a second null setting delta, instead, observer2 should only observe what observe1 sees in the beginning

**Screenshots**
![image](https://user-images.githubusercontent.com/25192107/140167874-9f0b3435-e1a5-46c2-9038-c1cdf5acc91d.png)

**Environment Information**
 - Browser chrome or any, check out the codesandbox
 - Yjs 13.5.17

**Comment by dmonad** [comment]
Hi @btezzxxt, thanks for the report. I implemented a test case for this and fixed the bug.

Due to the cleanup process, it is expected that you receive a second event. However, you are right that it should not emit `LIST_STYLES:null`. Now you just get an empty event.

I will release the fix shortly in 13.5.18.
