### ISSUE TITLE
Issue with version 13.5.20

### ISSUE THREAD

**Issue by lodka** [yjs/yjs#347]
A very big project(Jupyterlab) is using your library and when I was installing my own extension, I faced with this error

error /extensions/my-extension/node_modules/yjs: Command failed.
Exit code: 1
Command: node ./sponsor-y.js
Arguments: 
Directory: /extensions/my-extension/node_modules/yjs
Output:
internal/modules/cjs/loader.js:1149
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /extensions/my-extension/node_modules/yjs/sponsor-y.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1149:13)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}

Please resolve it ASAP

**Comment by dmonad** [comment]
Hi @lodka, I know, I wrote the Yjs integration into JupyterLab. I also wrote the tests and have JupyterLab running on my system. 

Could you please provide some more information? Please open a new issue and fill out the template. My first guess would be that you are running a very old nodejs version.

**Comment by qqdaiyu55** [comment]
Downgrade to NodeJS 12.13.0, issue gone. Looks like node js regression.
