### ISSUE TITLE
yjs ^13.5.18 - Typescript 4.4 throw error : Types of property 'gcFilter' are incompatible

### ISSUE THREAD

**Issue by dobernike** [yjs/yjs#349]
> Please save me some time and use the following template. In 90% of all issues I can't reproduce the problem because I don't know what exactly you are doing, in which environment, or which y-* version is responsible. Just use the following template even if you think the problem is obvious.

**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/

**Describe the bug**
Typescript throw error -  Types of property 'gcFilter' are incompatible. and Types of parameters 'arg0' and 'arg0' are incompatible. and  Types of property 'parent' are incompatible. ...

**To Reproduce**
1. Open console
2. See error

**Expected behavior**
Working w/o throwing errors in the console (or ts in IDE) like in 13.5.12

**Environment Information**
 - Node.js
 - "yjs": "13.5.12" working correct, but with "yjs": "^13.5.18" throw error

**Additional context**
yarn 2 berry (3.0) + typescript 4.4

**Comment by dmonad** [comment]
Please try again using the latest typescript version.

**Comment by dobernike** [comment]
> Please try again using the latest typescript version.

I can't use the latest typescript (4.5)
Because this version now conflicts with yarn 2 workspaces

**Comment by dmonad** [comment]
This is definitely a "you-issue". **I can't reproduce this issue (see linked commit above).** Furthermore, it's unlikely that typescript would ship a breaking change in a minor release.

yarn workspace projects are infinitely complex and there is no sane person that can ever understand them. Often you just need to recompile all type typings in your project. It's working fine with a basic setup. Anyway, that's 20 minutes of my life that I will not get back.

Next time, please provide a better issue description (the fact that you are using yarn 2 would have been helpful). Maintainers are not just free resources for help. I need you to do some debugging as well.
