### ISSUE TITLE
UndoManager.undo() does not trigger observeDeep observer on the object

### ISSUE THREAD

**Issue by kirill-konshin** [yjs/yjs#358]
> Please save me some time and use the following template. In 90% of all issues I can't reproduce the problem because I don't know what exactly you are doing, in which environment, or which y-* version is responsible. Just use the following template even if you think the problem is obvious.

**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [ ] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**

**To Reproduce**

```js
const UNDOABLE = 'UNDOABLE';

const map = doc.getMap('foo');

const undoManager = new Y.UndoManager(map, {
  captureTimeout: 0,
  trackedOrigins: new Set([UNDOABLE]),
});

map.observeDeep(() => console.log('observed'));

doc.transact(() => map.set('foo', 'bar'), UNDOABLE);
undoManager.undo();
```

`console.log('observed')` is NOT called.

**Expected behavior**

`console.log('observed')` called

**Environment Information**
 - Browser / Node.js [e.g. Chrome, Firefox, Node.js]: Chrome
 - Yjs version and the versions of the y-* modules you are using 13.5.17

**Comment by kirill-konshin** [comment]
Any updates here? Do you need more input?

**Comment by kirill-konshin** [comment]
@dmonad sorry to ping you directly, but can you please take a look at this issue?

**Comment by dmonad** [comment]
Hi @kirill-konshin,

I tested it and `console.log('observed')` is called two times. Once you insert the content and once you hit undo.

Also, an issue like this would have been caught by the tests before release. So I guess you had a filter on the logs? (happens to me sometimes too).

I'm closing this issue. But if you can create a code-sandbox of the latest Yjs release producing this bug, we can open it again.
