### ISSUE TITLE
Expose `convertUpdateFormatV1ToV2`

### ISSUE THREAD

**Issue by HalfVoxel** [yjs/yjs#363]
**Is your feature request related to a problem? Please describe.**
It sure would be nice to be able to use `convertUpdateFormatV1ToV2` myself for migrations. As it is right now, the function is not exported externally, from what I can see.

**Describe the solution you'd like**
Export `convertUpdateFormatV1ToV2` from the package.

**Describe alternatives you've considered**
Maybe also  `convertUpdateFormatV2ToV1`, though that seems less useful.

CC: @ViktorQvarfordt

**Comment by dmonad** [comment]
Done. I exported both functions and will release a new version shortly.
