### ISSUE TITLE
encodeStateAsUpdate(doc1, vectorOfDoc2) don't return empty update between 2 equal docs

### ISSUE THREAD

**Issue by evilfant** [yjs/yjs#374]
**Describe the bug**
**To Reproduce**
1. If create doc and make next changes with it's yText
```js
const doc1 = new Doc();
const yText1 = doc1.getText('code');

yText1.insert(0, 'a');
yText1.delete(0, 1);
yText1.insert(0, 'b');
```
2. Then create identical doc
```js
const doc2 = new Doc();
applyUpdate(doc2, encodeStateAsUpdate(doc1));
```
3. After that take `vector` of the first doc and calc diff between identical docs. Calculated update won't be empty
It will have a `DeleteItem`
```js
const vector1 = encodeStateVector(doc1);

const diff1 = encodeStateAsUpdate(doc2, vector1);

// not empty update, but it should
logUpdate(diff1);
/*
Structs:  []
DeleteSet:  DeleteSet { clients: Map { 1241621181 => [ [DeleteItem] ] } }
*/
```
[codesandbox1](https://codesandbox.io/s/tender-benz-vi9f3?file=/src/index.js)
It works fine if remove the line `yText1.delete(0, 1);`

It also reproduces with only one doc [codesandbox2](https://codesandbox.io/s/eloquent-glade-tqx47?file=/src/index.js)

**Expected behavior**
Update should contains an empty DeleteSet

**Environment Information**
 - Node.js / Browser
 - yjs v13.5.24

**Comment by mlajtos** [comment]
> Deletes are not tracked by state vectors, hence clients always exchange all deletes with each other. This is encoded very efficiently and it does not make sense to optimize this further. Not tracking this kind of information (we don't have to assign a lamport timestamp to each delete operation) also allows us to do further compressing of the data. The advantage is that we have a much smaller initial load. The disadvantage is that we always have a small load of deletes even when we are fully synced.

Source: https://github.com/yjs/yjs/issues/346#issuecomment-963955415

**Comment by dmonad** [comment]
Thank you @mlajtos!

Closing this issue.
