### ISSUE TITLE
Avast phishing warning on https://coronavirustechhandbook.com/ 

### ISSUE THREAD

**Issue by leehambley** [yjs/yjs#377]
Forgive me please for ignoring the reporting template, Avast AV (bossware installed on my corporate laptop) catches a warning for this domain https://coronavirustechhandbook.com/ 

![image](https://user-images.githubusercontent.com/18952/149950293-a3bc56d3-763a-43e8-9616-61624d8ef8e6.png)

**Comment by georeith** [comment]
What does this have to do with Yjs?

**Comment by leehambley** [comment]
The link to a phishing site is prominently displayed in your README 
![image](https://user-images.githubusercontent.com/18952/150779514-4d36b880-5bbd-49ef-ac4e-aa662cce8f36.png)

**Comment by dmonad** [comment]
Thanks @leehambley. I can't imagine that there is a security thread on that website. However, I removed the entry because the author doesn't maintain the project anymore.
