### ISSUE TITLE
Multiple document transactions

### ISSUE THREAD

**Issue by ChasLui** [yjs/yjs#389]
**Checklist**

[ ] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
[x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Is your feature request related to a problem? Please describe.**
When I need to modify the content of two documents in one transaction, I can't do it.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dmonad** [comment]
You can nest transactions, but it doesn't guarantee that these changes will be applied simultaneously on remote documents.

```js
doc1.transact(() => doc2.transact(() => {
  // changes go here..
}))
```
