### ISSUE TITLE
Undoing text formatting delete corrupts peer state

### ISSUE THREAD

**Issue by dkuhnert** [yjs/yjs#392]
**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
Undoing text formatting delete corrupts peer state.

Format changes step by step:
- Source:
Attack ships on fire off the shoulder of Orion.
- Change 1:
Attack ships `{bold:true}`on fire`{bold:null}` off the shoulder of Orion.
- Change 2:
Attack ships `{bold:true}`on `{bold:null}`fire off the shoulder of Orion.
- Undo Change 2:
  - Doc 1:
Attack ships `{bold:true}`on fire`{bold:null}` off the shoulder of Orion.
  - Doc 2 (using sync):
Attack ships `{bold:true}`on fire off the shoulder of Orion.

**To Reproduce**
Run the following test case:

```js
/**
 * Undo text formatting delete should not corrupt peer state.
 * 
 * @param {t.TestCase} tc
 */
export const testUndoDeleteTextFormat = tc => {
  const doc = new Y.Doc()
  const text = doc.getText()
  text.insert(0, 'Attack ships on fire off the shoulder of Orion.')
  const doc2 = new Y.Doc()
  const text2 = doc2.getText();
  Y.applyUpdate(doc2, Y.encodeStateAsUpdate(doc))
  const undoManager = new Y.UndoManager(text)

  text.format(13, 7, { bold: true })
  undoManager.stopCapturing()
  Y.applyUpdate(doc2, Y.encodeStateAsUpdate(doc))
  
  text.format(16, 4, { bold: null })
  undoManager.stopCapturing()
  Y.applyUpdate(doc2, Y.encodeStateAsUpdate(doc))
  
  undoManager.undo()
  Y.applyUpdate(doc2, Y.encodeStateAsUpdate(doc))

  const expect = [
    { insert: 'Attack ships ' },
    {
      insert: 'on fire',
      attributes: { bold: true }
    },
    { insert: ' off the shoulder of Orion.' }
  ]
  t.compare(text.toDelta(), expect)
  t.compare(text2.toDelta(), expect)
  
  /*
  text2.toDelta() = [
    { insert: 'Attack ships ' },
    {
      insert: 'on fire off the shoulder of Orion.',
      attributes: { bold: true }
    }
  ]
  */
}
```

**Expected behavior**
After undoing the last change and syncing doc1 to doc2 the text should be the same in doc1 and doc2.

**Environment Information**
- yjs@13.5.27 (058a50285c3ad959b09211b48d6a91b3951d0db7)
 - nodejs@16.13.0

**Comment by dmonad** [comment]
There are some cases where merging formatting attributes doesn't resolve in the ideal solution. Especially when undoing formats on the same ranges concurrently, we might not have ideal outcomes. Yjs performs a lot of cleanup to reduce memory consumption and make it viable in practice. The cleanup process happens after operations are applied and will eventually get propagated to all clients.

Can you please make sure that all clients are synced by performing the following at the end?

```js
Y.applyUpdate(doc2, Y.encodeStateAsUpdate(doc))
Y.applyUpdate(doc, Y.encodeStateAsUpdate(doc2))
Y.applyUpdate(doc2, Y.encodeStateAsUpdate(doc))
Y.applyUpdate(doc, Y.encodeStateAsUpdate(doc2))
```

I'm not sure if a double merge is necessary, but we need to ensure that all updates are really propagated (even the cleanup events after a remote update is applied).

**Comment by dkuhnert** [comment]
Yeah, when i sync the doc2 back to doc1 both documents end up with the invalid formatting. So the word "corrupts" is somewhat misleading as the state is still eventually consistent 😄
