### ISSUE TITLE
Redis not receiving updates

### ISSUE THREAD

**Issue by karthik-sketchnote** [yjs/yjs#394]
Bug Description
When opening a new document, Redis captures all keystrokes and updates are recorded properly on the Redis server. Randomly though, after leaving the document idle for a little time (no exact time period, but most typically about 4 - 5 minutes), while browsing other tabs, subsequent updates to the document stop being registered by Redis. When the browser is then refreshed, it fetches stale data from Redis since Redis now no longer has the most recent updates. Please provide any inputs you may find could be worth trying at our end. Our users are reporting this as data loss and we are at a roadblock trying to fix this issue. Mentioning @dmonad as well.

**To Reproduce**
We are using the hocuspocus library, however could not deduce any concrete reason for this behaviour. Refreshing the browser, though, re-establishes the expected behaviour, and Redis once again starts capturing keystrokes.

**Expected behavior**
Expecting Redis to either capture updates or reconnect automatically if the connection is disrupted somehow

**Screenshots**
Screen capture of when redis is capturing user input - on the left is the browser, on the right is the redis server monitor
https://www.loom.com/share/a5200704d5634392a10db4a01d59da73

Screen capture of when redis stops capturing user input
https://www.loom.com/share/d1335573bf2c42dfa8e51d0c33f346b4

Additional information:
We can confirm that the websocket connection between the client and the hocuspocus server is intact, because the changes from the hocuspocus server are being persisted properly into the connected database, however only Redis does not get the updates.

**Environment Information**
 - Browser / Node.js Brave, Node.js v14.15.1

**Comment by dmonad** [comment]
Hocuspocus is a separate project that is not maintained by me. Please open an issue on their repository.
