### ISSUE TITLE
is:issue is:open Change 'destroy' to 'release'

### ISSUE THREAD

**Issue by Flamenco** [yjs/yjs#396]
This is just a teeny-tiny idea for the next major release.

```
let ydoc:Y.Doc = await getYDoc()
await ydoc.release()
```

is more in line with the result of the function, versus

```
let ydoc:Y.Doc = await getYDoc()
await ydoc.destroy()
```

**Comment by dmonad** [comment]
In lack of existing conventions or a better name, I call the "deconstructor" `destroy()` consistently across my codebases.

There are many active parts bound to a Yjs document. A `free()` or `release()` feels too passive as there is more happening than simply releasing memory. For example, we actively destroy all related editor bindings. Destroying a document actively changes the environment so the name should express that (ie. we are not just releasing some unneeded memory).

I'm very open to more ideas. 

However, I'm probably not going for `release()`, so I'm closing the issue. But feel free to post some more ideas.

**Comment by Flamenco** [comment]
Understood, @dmonad .  It seem as the following happens.

1. The ydoc removes subdocuments
2. The superclass Observable (also using `destroy` syntax) removes observers.

How about `close`.

**Comment by dmonad** [comment]
Furthermore, event handlers & type observers are unregistered. A `destroy` event is fired beforehand. Everyone who "bound" to that Yjs document should also destroy themselves.

Personally, I don't see any advantages in `close`. This sounds more like something like a connection or stream would use.

**Comment by Flamenco** [comment]
Yes, I'm not sure if there is a better word in English.  Perhaps `detach`?

**Comment by dmonad** [comment]
`terminate` is more used for machines that you want to force to stop. Often used to end processes for example.

`detach` is not really an improvement and is often used by UI libraries to "detach" from the dom. Also confusing.

I think we are going to stay with `destroy`.

**Comment by Flamenco** [comment]
Well `destroy` is probably better than `delete`.  Thanks for considering!    👍
