### ISSUE TITLE
Inspect the shared types in a document without prior knowledge of what those types are

### ISSUE THREAD

**Issue by reivilibre** [yjs/yjs#399]
Hi there,

I'm trying to do something a little bit nasty and dump an entire `Y.Doc` to JSON/CBOR-like structures (ignoring history; just the latest state) so that a non-JavaScript (Rust) program can read some interesting parts of the documents and store some data about it in a tracking database.

My first approach to this was to iterate through `doc.share.entries()` and dump each 'shared type' using a recursive helper function. It seemed to work OK.

However, it all fell over when I did this on a freshly-loaded document (as opposed to a document that I created and modified before dumping). From reading up about it, I think this is because I haven't called `doc.getMap("wombat")` and so on.

Is it possible to dump the structure of the document without knowing which types are being used (or to find out what the types are?).

If it's a 'No', that's fine — I can just encode it as a map or hardcode it, but I suppose I was just surprised to see no way to do it.

**Comment by dmonad** [comment]
Hi @reivilibre,

please go through the proper channels and read the description of the template that you ignored.

**Comment by reivilibre** [comment]
Hi dmonad,

I'm sorry for going to the wrong place; I forgot this project has a forum and I'm used to small projects where this kind of question would have been in order on the issue tracker.

However I must admit I'm a little bit lost by

> read the description of the template that you ignored.

I don't know what this template is — I haven't ignored anything that I'm aware of (?). If it's obvious, sorry for missing it, but even now that you mention it I don't know what this is.

**Comment by dmonad** [comment]
When you create an issue in one of these repositories, the initial content (the issue template) describes that this is not a place for questions.

It's not a big thing. But please help me to be more efficient. The forum is searchable and you'll already find similar questions to yours.

Gesendet von ProtonMail mobile

-------- Original Message --------

**Comment by reivilibre** [comment]
That's fair enough, but for what it's worth, the initial content just says 'Leave a comment' on mine! :confused:
(Maybe it's something on my end, though..)

![image](https://user-images.githubusercontent.com/38398653/158010985-4299cbd3-c9c0-4804-8235-2b26ebe2eaed.png)
