### ISSUE TITLE
Can't set limit for `UndoManager` - it is corrupt objects

### ISSUE THREAD

**Issue by vitonsky** [yjs/yjs#400]
**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**

I can't implement limit for `UndoManager`.
When i try to manually remove old objects like this `undoManager.undoStack = undoManager.undoStack.slice(-10);` then i got unpredictable behavior of Yjs map - some objects will corrupted.

How we can correctly implement a limit of undoable transactions?

**To Reproduce**
1. Make instance of `UndoManager`
2. Do 20 actions
3. Do `undoManager.undoStack = undoManager.undoStack.slice(-10);` to remove old actions

**Expected behavior**
Yjs Map is not corrupted and we can undo only 10 actions

**Actial behavior**
We can undo only 10 actions, but some objects is corrupted in Yjs Map

**Environment Information**
 - Browsers
 - Yjs 13.5.27

**Additional context**

I need to implement limit of actions entries which is keeps in the `UndoManager` to avoid memory leaks while intensive long sessions.

How can i do it?

**Comment by dmonad** [comment]
How is the data corrupted? 

Can you please provide a minimal example of how to reproduce the erroneous behavior?

**Comment by vitonsky** [comment]
It's not a your bug, it's my bug. Library works fine. So i close this issue. Thanks
