### ISSUE TITLE
decodeUpdateV2 always use UpdateDecoderV1

### ISSUE THREAD

**Issue by alderzhang** [yjs/yjs#403]
`Y.decodeUpdate` method does not use the input parameter `YDecode`, it always use `UpdateDecoderV1` as decoder, did you miss a change?

branch: `main`

<img width="631" alt="image" src="https://user-images.githubusercontent.com/8778642/158321888-4e131b3f-6d83-4d10-8a79-0c6b5ba2f82f.png">

**Comment by alderzhang** [comment]
#404 try to fix it.

**Comment by dmonad** [comment]
I merged your PR.
