### ISSUE TITLE
Yjs was already imported.

### ISSUE THREAD

**Issue by PhilGarb** [yjs/yjs#410]
**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [ ] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
I get the console warning: `Yjs was already imported. Importing different versions of Yjs often leads to issues.` In the codebase you warn to take this seriously, because it may introduce bugs: https://github.com/yjs/yjs/blob/46e108f34583fda3d85ea165daa7c4c979b22728/src/index.js#L103-L114

**To Reproduce**

Go to Reproduction: https://stackblitz.com/edit/nextjs-jjwdo2?file=pages/index.js
After next js started the error appears in the console output.
I my app it also appears in the browser console I am not sure about how to reproduce that.

**Expected behavior**
Only one yjs version should be imported.

**Environment Information**
- Browser: Chrome/Firefox/Safari
- Node js version: 14.19.0/16.14.0 
- yjs 13.5.30; y-websocket 1.3.18; y-indexeddb 9.0.7; y-protocols 1.0.5

**Additional context**

I do not import multiple versions (by version number).
I have the feeling that I am indeed importing a commonjs and an esm version, as described in the error, because the issue started appearing after upgrading to next js 12 recently. They introduced native esm support in that release: https://nextjs.org/blog/next-12#es-modules-support-and-url-imports.

Any guidance about why this issue might appear would be fantastic.

Thank you!

**Comment by dmonad** [comment]
Hi @PhilGarb,

This is probably due to some live reloading issue. Some frameworks support swapping out components in real time without reloading the window. I came in touch with a different live reload feature a few years back. In order to prevent sync issues, we had to configure it to reload all components that are connected to Yjs so it works correctly. 

As long as you don't experience any sync issues, you are probably fine. However, this issue should definitely not happen in the production build.

If it does, you should probably bring this up with the authors of next (or maybe stackblitz if this is specific to them). It seems inefficient to load modules twice.

**Comment by PhilGarb** [comment]
How did I not think about hot reloading. That is probably the reason. I do actually have sync issues with y-indexeddb, but this seems to be related to Valtio-yjs https://github.com/dai-shi/valtio-yjs/issues/26.
Thank you for the prompt response.

**Comment by jacobcoro** [comment]
@PhilGarb Were you able to solve this? I'm having the same issue. I don't think it is hot-reloading because this is also happening in production.

I'm having some sync issues but I'm not sure it has to do with this warning or not

**Comment by dmonad** [comment]
@jacobcoro If you are having sync issues, it almost certainly has something to do with the error message.

The most common error is that users import both the esm and the cjs version of Yjs. Sometimes they use some complex lerna setup that installs different versions of Yjs. 

Just some hints for the people looking for a solution..

**Comment by jacobcoro** [comment]
Just fixed it! Turns out that was definitely the issue. 
```js
// next.config.js
const path = require('path');
module.exports = {
  webpack: (config, { webpack }) => {
    config.resolve.alias.yjs = path.resolve('./node_modules/yjs');
    return config;
  },
};
```
Force next to only use one copy of yjs

**Comment by Himself65** [comment]
> Just fixed it! Turns out that was definitely the issue.
> 
> ```js
> // next.config.js
> const path = require('path');
> module.exports = {
>   webpack: (config, { webpack }) => {
>     config.resolve.alias.yjs = path.resolve('./node_modules/yjs');
>     return config;
>   },
> };
> ```
> 
> Force next to only use one copy of yjs

This doesn't work for me

**Comment by andrevenancio** [comment]
also why destructure webpack if its not used?
