### ISSUE TITLE
Unreadable document created in certain cases

### ISSUE THREAD

**Issue by tmathew0309** [yjs/yjs#417]
**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [ ] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
Getting the following error when reading in a serialized document: 

```
org.graalvm.polyglot.PolyglotException: Uncaught TypeError: Cannot read properties of undefined (reading 'origin')
	at <js>.integrate(yjsBackendBundle.js:19628)
	at <js>.integrateStructs(yjsBackendBundle.js:11897)
	at <js>.:=>(yjsBackendBundle.js:11962)
	at <js>.transact(yjsBackendBundle.js:13628)
	at <js>.readUpdateV2(yjsBackendBundle.js:11950)
	at <js>.applyUpdateV2(yjsBackendBundle.js:12045)
	at <js>.applyUpdate(yjsBackendBundle.js:12059)
```

Document is now effectively corrupted and the user has lost what they were working on.

**To Reproduce**
We haven't been able to reproduce this error yet but two separate clients have run into it over the course of a week. Will continue trying to narrow down what situations seem to cause it. 

**Expected behavior**
Serialized document is always readable 

**Screenshots**

**Environment Information**
 - Happens on both browser and node. x
 - yjs: `13.5.18`

**Additional context**
We use a mostly vanilla setup but our clients and server exchange state vectors every minute to calculate and exchange diffs using  `encodeStateVectorFromUpdate` and `diffUpdate`. Not sure if that helps narrow down why this kind of issue might arise.

**Comment by nllevin** [comment]
Hi @dmonad, we ran into this issue again recently. Curious whether you have any updates or any guesses about how documents end up in this unreadable state?

**Comment by dmonad** [comment]
This is fixed in the last release. Please open a new issue if it still persists.
