### ISSUE TITLE
YJS  remote cursor usage

### ISSUE THREAD

**Issue by parthgurudeo** [yjs/yjs#425]
Hey, I was just using Yjs library and wanted to use remote cursor classes, so the class is being applied to the one selecting text on that pc only rather it should reflect on another system. So can anyone suggest to me how to implement it? Also i don't know how to use this awareness.on("update", () => ...)); for different client id's to apply different styles.
Thank you

**Comment by dmonad** [comment]
This is not a bug report

**Comment by dmonad** [comment]
The ticket template clearly states where to ask questions.
Also, .. just invest a bit of time and read the documentation before you ask questions.
