### ISSUE TITLE
Decouple core undo manager logic with additional undo features (like timeout)

### ISSUE THREAD

**Issue by PatrickShaw** [yjs/yjs#433]
**Checklist**

[x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
[x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Is your feature request related to a problem? Please describe.**
For the project I'm working on, `Y.UndoManager` is going to be super useful ❤️. However, we don't need a lot of the features that are bundled into it. For instance, we have no need for `captureTimeout` and so we end up disabling it so we end up with a form of [abstraction inversion](https://en.wikipedia.org/wiki/Abstraction_inversion) where we're creating a lower level undo manager from a higher one. This adds unnecessary complexity and opens us up to bugs we otherwise wouldn't run into like #431

Hope that makes sense :)

**Describe the solution you'd like**
I propose we decouple the timeout logic and any other non-bare-minimum features from `Y.UndoManager` and create `Y.BaseUndoManager` (core functionality) + a bunch of utilities (additional functionality). We can then compose `Y.UndoManager` from those new APIs. Something like this is roughly how imagine it working:

```typescript
interface UndoManagerInterface {
  // ...
}

export class BaseUndoManager {
  // ...
}

export const withCaptureTimeout = (manager: UndoManagerInterface, timeout: number): UndoManagerInterface => {
  // ...
};

export class UndoManager implements UndoManagerInterface {
  private readonly internalManager: UndoManagerInterface;
  constructor({
     captureTimeout,
     //...
  }) {
    this.internalManager = withCaptureTimeout(new BaseUndoManager(/* ... */), captureTimeout);
  }
  
  // ...
}
```

**Describe alternatives you've considered**
None at the moment.

**Comment by PatrickShaw** [comment]
I'd be willing to work on this at some point if we're in agreement :)

**Comment by dmonad** [comment]
Hi Patrick,

I like to separate things whenever possible and provide features as optional imports whenever possible.

However, the proposed change will probably lead to code duplication and increase complexity which will make it harder to maintain. Try it out. `captureTimeout` adds about 4 lines of code to the codebase, and I feel it doesn't make sense to maintain two separate undo managers simply to remove this feature.
