### ISSUE TITLE
Missing export for encodeStateVectorV2

### ISSUE THREAD

**Issue by reijne** [yjs/yjs#441]
**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
The function `encodeStateVectorV2` is defined in src/utils/encoding.d.ts, however, it is not exported in dist/src.
Therefore, when importing from 'yjs', the function does not exist.

**To Reproduce**
1. `import * as Y from 'yjs'`
2. `Y.encodeStateVectorV2(...)`
3. Error: property does not exist

**Expected behavior**
Like the other V2 equivalent functions, I expect the property to be exported in dist/src, allowing usage when importing yjs. For example `encodeSnapshotV2`

**Environment Information**
 - Browser independent. Used: Chrome
 - "yjs": "^13.5.24"

**Comment by Hideman85** [comment]
Same issue here

**Comment by chris-top-legal** [comment]
Same issue here

**Comment by dmonad** [comment]
The internal function Y.encodeStateVectorV1 is currently the same as encodeStateVectorV2. This might change in the future without breaking the exposed API. encodeStateVectorV2 is strictly for internal usage (for consistency). You should use Y.encodeStateVector without suffix.
