### ISSUE TITLE
Is it safe to use several instances Yjs in application if it's never interact?

### ISSUE THREAD

**Issue by vitonsky** [yjs/yjs#446]
Hi, we have application that build with webpack and contains of federated modules with isolated dependencies.

Recently we had warnings like in issue https://github.com/yjs/yjs/issues/438 I have question about it.

Is it safe to have 2 isolated modules if each of it have own Yjs package?

This modules is not interact with each other at all or interact by some API, but code from one module is never use Yjs from another module.

Maybe Yjs is write some objects to a global object and 2 imports from different packages may rewrite something important and lead us to problems?

I've read this commit https://github.com/yjs/yjs/commit/cbddf6ef90be3493661bb36a416627f86a0700b6 and i guess that Yjs is write to global object only `importIdentifier`, and for our specific case we may use 2 different Yjs package, because inside one module the code use only one package always

**Comment by dmonad** [comment]
Please use the discussion board for questions

**Comment by vitonsky** [comment]
@dmonad i've ask my question on https://discuss.yjs.dev/ 3 days ago and its still in pending status and even didn't publish.

Could you answer here or approve my question there? It's important question about new warning
