### ISSUE TITLE
Y.Event delta does not include information about pushed element to the Y.Array

### ISSUE THREAD

**Issue by um-synth** [yjs/yjs#450]
**Describe the bug**

I would like to know how we could identify from the Y.Event that sth was added at the end of the array. We are listening for all the changes on the Y.Map that can also include Y.Arrays. Based on the Y.Event we receive from `observeDeep` listener on Y.Map object we try to figure out which parts of the nested structure were updated and how (based on `path` and `delta`). However, in case we push an item to the end of the array delta is just empty.

Is there any reason for that or do you believe that’s a bug?

**To Reproduce**
Here is a tiny code where this can be seen: https://playcode.io/935939/

**Expected behavior**
I would expect that delta would also describe the item being added to the end of the array.

**Comment by dmonad** [comment]
Hi @um-synth, 

`event.changes` is a computed property that can only be computed during the event. A lot of metadata, that is required for computing the changes, is removed after the transaction (after the event emitter is fired). I realize that this is not completely obvious. But there is little I can do about that. 

If you adapt your code as follows, it will work as expected:

```js
const Y = require("yjs");

const doc = new Y.Doc();
const target = doc.getMap("test_root_map");

const yArray = new Y.Array();
yArray.push([1, 2, 3]);
target.set("array", yArray);

/*********************************
 * APPLY CHANGES
 *********************************/
const allEvents = [];
target.observeDeep((events) => {
  events.forEach((event) => {
    allEvents.push(event.changes);
  });
});

const array = target.get("array");
array.insert(3, [4]);

console.log('Updated Y.js document: ', target.toJSON());
allEvents.forEach((event) => {
  console.log('EVENT CHANGES: ', event);
});

```

**Comment by um-synth** [comment]
Hi @dmonad.

First, thank you for the quick reply. Though I would have a follow-up question. 
When you say that after transaction is finished, some things are cleaned up. How does that affect the remote clients? Can sth similar also happen to remote clients or is that specific to the local client who is in control of the active transaction?
