### ISSUE TITLE
copy doc not work

### ISSUE THREAD

**Issue by cqh963852** [yjs/yjs#451]
https://github.com/yjs/docs/blob/23db6c9f09b36660835f3a02e0009040eb6d5167/api/subdocuments.md?plain=1#L64-L79

The document said the subdocument can be copied.

But It not synced after copy.

![image](https://user-images.githubusercontent.com/17702287/182885673-d81d9c95-be24-469b-9a62-202cc109eff2.png)

Is there anything I've lost that I could use to sync?

**Comment by dmonad** [comment]
Hi @cqh963852,

The doc also says that `It is up to the providers to sync subdocuments. `. Once the provider recognizes that a doc with an existing guid is added, it should sync the subdocuments automatically via network or directly.

Note that some providers will sync these documents **eventually** (e.g. over the network). If your custom provider supports subdocuments, then they will eventually sync.

**Comment by cqh963852** [comment]
> The doc also says that `It is up to the providers to sync subdocuments. `. Once the provider recognizes that a doc with an existing guid is added, it should sync the subdocuments automatically via network or directly.
> 
> Note that some providers will sync these documents **eventually** (e.g. over the network). If your custom provider supports subdocuments, then they will eventually sync.

Thanks for your reminder. I should also sync it on the server side.
