### ISSUE TITLE
Help with using y-js and yjs monaco editor binder with Action Cable rails

### ISSUE THREAD

**Issue by ahmadhaidarahmad** [yjs/yjs#467]
**Checklist**

**Describe the solution you'd like**

First of all thank you a lot for the help in advance.
Currently I need to use action cable websockets instead on y-websocket to be able to work with the clients I have in my db and to save the code in my db as well but I’m not figuring it and I need a help to start this and use the broadcasted data inside y-js client. @dmonad  if you can help me in doing this and creating a new provider for my rails app that would be really great and would be appreciated a lot. 
Thank you 🙏

**Comment by dmonad** [comment]
Hi @ahmadhaidarahmad,

this is not the right place to ask questions. Questions go to discuss.yjs.dev.
