### ISSUE TITLE
The code point cannot be greater than 255

### ISSUE THREAD

**Issue by leegean** [yjs/yjs#470]
Here is a snippet from the encoding.js file:

```

1. export const writeVarString = (encoder, str) => {
2.   const encodedString = unescape(encodeURIComponent(str))
3.   const len = encodedString.length
4.   writeVarUint(encoder, len)
5.   for (let i = 0; i < len; i++) {
6.     write(encoder, /** @type {number} */ (encodedString.codePointAt(i)))
7.   }
8. }

```
In line 6, information is lost if the code point for a character is greater than an unsigned 8-bit integer.For example, Asian languages

**Comment by dmonad** [comment]
The string is normalized first. lib0/encoding encodes into valid utf8 (which supports Asian character sets).

**Comment by leegean** [comment]
Does it cause the encoded bytes to be too large, a string like “😃thingć中文”.

Is that better?Remove the code of encoding into valid utf-8,rewrite write() method to writeVarUint(),like this:

export const writeVarString = (encoder, str) => {
  const encodedString = str
  const len = encodedString.length
  writeVarUint(encoder, len)
  for (let i = 0; i < len; i++) {
    writeVarUint(encoder, /** @type {number} */ (encodedString.codePointAt(i)))
  }
}

**Comment by dmonad** [comment]
If you want to contribute then please make some research first. The intention ist to encode into utf8 and don't come up with another encoding scheme. If you find a bug, report it. The text you provided can be encoded and decoded again in the current approach.
