### ISSUE TITLE
Data sync issue with nested array in map 

### ISSUE THREAD

**Issue by wangzuo** [yjs/yjs#483]
Below is my testing for the case, which fails and the list is ["testing2"] instead of ["testing1", "testing2"]

```javascript
test("yjs nested array in map", () => {
  const doc1 = new Y.Doc();
  const doc2 = new Y.Doc();
  doc1.on("update", (update) => {
    Y.applyUpdate(doc2, update);
  });
  doc2.on("update", (update) => {
    Y.applyUpdate(doc1, update);
  });

  const map1 = doc1.getMap("story");
  const list1 = new Y.Array();
  map1.set("list", list1);
  list1.push(["testing1"]);

  const map2 = doc1.getMap("story");
  const list2 = new Y.Array();
  map2.set("list", list2);
  list2.push(["testing2"]);

  expect(doc1.getMap("story").toJSON()).toEqual(doc2.getMap("story").toJSON());
  expect(doc2.getMap("story").toJSON()).toEqual({
    list: ["testing1", "testing2"],
  });
});
```

I don't know if this is the correct way to work with nested data structure in yjs, thank you for any help.

**Comment by dmonad** [comment]
You are setting the `"list"` property first on `doc1` and then overwrite it with a new `Y.Array` in `doc2`. Even if this was a concurrent action, the last writer would "win" and only one `Y.Array` would be preserved.

You can simply do `ydoc.getArray("list")` to create a list that can be accessed by accessed by all clients. Or you need to wait for one client to set `list` until you can access it in the other client.
