### ISSUE TITLE
Y.encodeStateAsUpdate returns different value for the same ydoc

### ISSUE THREAD

**Issue by vineetdigit** [yjs/yjs#491]
**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
`Y.encodeStateAsUpdate` some times returns different value for the exact same ydoc

**To Reproduce**

**Steps to reproduce the behavior requires running it via a bash script**
1. Create a file `yupdate.js` (code below)
2. Create a shell script `run.sh` (code below) and make it executable (chmod +x run.sh)
3. Run the shell script `./run.sh` and observe that some runs return a different value

**yupdate.js**
```
const Y = require("yjs");

const ydoc = new Y.Doc();

ydoc.getMap("foo").set("a", "a");
ydoc.getMap("foo").set("b", "b");
ydoc.getMap("foo").set("c", "c");

ydoc.getMap("bar").set("d", "d");
ydoc.getMap("bar").set("e", []);
ydoc.getMap("bar").set("f", []);

ydoc.getArray("0").insert(0, []);
ydoc.getArray("1").insert(0, []);
ydoc.getArray("2").insert(0, []);
ydoc.getArray("3").insert(0, []);
ydoc.getArray("4").insert(0, []);

console.log(Y.encodeStateAsUpdate(ydoc).length);
```
**run.sh**
```
#!/bin/bash
for (( ; ; ))
do
  node yupdate.js
done
```
**Expected behavior**
Y.encodeStateAsUpdate should return same value for every run with the given ydoc

**Actual behavior**
Here is the output I observe

```
$ ./run.sh
79
79
79
79
78 ← here
79
79
79
79
79
79
79
79
79
79
78 ← here
79
79
79
79
79
78 ← here
```

**Environment Information**
 - Node.js (v16.15.0) 
 - Yjs version 13.5.44

**Comment by dmonad** [comment]
This is the expected behavior and can't be changed.

Every client session generates a random "client-id". This is to ensure that updates from different clients are unique. Otherwise, we wouldn't be able to distinguish between two different client operations.

**Comment by vineetdigit** [comment]
Thanks for your response @dmonad. Intuitively its logical to think of "clientID" as "sessionID" instead.

Are there other valeus besides clientID that can cause the same ydoc to generate different update?
