### ISSUE TITLE
Applying Updates From Doc A to Doc B End Up With Different `toDelta()` on the YText state.

### ISSUE THREAD

**Issue by deeg** [yjs/yjs#494]
> Please save me some time and use the following template. In 90% of all issues I can't reproduce the problem because I don't know what exactly you are doing, in which environment, or which y-* version is responsible. Just use the following template even if you think the problem is obvious.

**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**

Using `applyUpdate` to apply updates from Doc A to Doc B ends up with different end states when calling `toDelta()` afterwards

**To Reproduce**

1. Have two documents - A & B
2. Listen to for Doc A and apply all updates to Doc B 
    - `ydoc.on('update', (update) => {
  applyUpdate(yDocApplyUpdates, update);
})`
4. Apply a set of 5 Deltas to YText of Doc A - initial content, with 4 updates to the initial content

After taking the steps - compare the `toDelta()` result of YText of Doc A & Doc B and notice there is a difference.

This is the same difference as comparing the transformations without YJS (Delta Only) and Doc B YText `toDelta`

```
[ { retain: 125 }, { retain: 29, attributes: { list: [Object] } } ]
```

In our real world example this difference is sent out as an extra change event to all clients connected, causing their editor to get corrupted since this Delta is incorrect and not supposed to be applied. 

**Expected behavior**

When applying updates from Doc A to Doc B they should both end up in the same state when calling `toDelta` on the yDoc.

**Additional Notes**

1. If I put the 4 updates into a single transaction everything works as expected, but in our editor we apply al editor changes to the YText directly after it happens, all in their own transaction.

**Code**

See example in StackBlitz. View the console for the output.

https://stackblitz.com/edit/typescript-pxr92g?file=index.ts,package.json

Notice the issue does not happen when downgrading YJS. The last good version is yjs@13.5.35.

https://stackblitz.com/edit/typescript-rrsgfq?file=index.ts,package.json

**Environment Information**
- YJS `13.5.44`

The bug started in yjs@13.5.36, it was working as expected in yjs@13.5.35

Changes in release that caused it: https://github.com/yjs/yjs/compare/v13.5.35...v13.5.36

**Comment by dmonad** [comment]
Hi @deeg,

Thanks for creating an reproducible example. I Please have a look at my comment in #492 . This is the same issue. You need to sync changes both ways (from ydoc to yDocApplyUpdates and back). Just add this to the file:

```js
yDocApplyUpdates.on('update', (update) => {
  applyUpdate(ydoc, update);
});
```
