### ISSUE TITLE
Package subpath './dist/logging.cjs' is not defined by "exports" in '.../node_modules/lib0/package.json'

### ISSUE THREAD

**Issue by lin52025i** [yjs/yjs#512]
With the release of the latest version of `lib0`, the `. /dist/logging.cjs` to `. /logging`.
The use of `var logging = require('lib0/dist/logging.cjs')` in `yjs/dist/yjs.cjs` to introduce the corresponding functionality makes it inapplicable in the newer version of `lib0`.

> lib0/package.json `v0.2.70`
<img width="801" alt="image" src="https://user-images.githubusercontent.com/87741822/226576457-184c341e-8fc1-4837-934f-c0d0966d8a1d.png">

> lib0/package.json `v0.2.69`
<img width="666" alt="image" src="https://user-images.githubusercontent.com/87741822/226577021-3dc4a749-36a0-4738-9033-b1940a87233b.png">

> yjs/dist/yjs.cjs

![image](https://user-images.githubusercontent.com/87741822/226578486-ac6076f2-059e-4893-af8b-429567635be9.png)

> yjs/package.json

![image](https://user-images.githubusercontent.com/87741822/226578698-dd4a404f-61fa-4221-830a-ee0a6a71e747.png)

So would you consider locking the `lib0` version (<=0.2.69) or adjusting the corresponding introduction?

**Comment by dmonad** [comment]
Hi @lin52025i,

I think this should be fixed in `lib0@0.2.72`. Could you please check?

The recommended way to import/require lib0 is to do `require(lib0/logging)` / `import * as l from 'lib0/logging'`. This should work if you are using `node@>=14`.

**Comment by lin52025i** [comment]
Yes, this definition has been added to `lib0@0.2.72` in the latest version.

**Comment by lin52025i** [comment]
> Hi @lin52025i,
> 
> I think this should be fixed in `lib0@0.2.72`. Could you please check?
> 
> The recommended way to import/require lib0 is to do `require(lib0/logging)` / `import * as l from 'lib0/logging'`. This should work if you are using `node@>=14`.

Think you!!!

**Comment by lin52025i** [comment]
> Hi @lin52025i,
> 
> I think this should be fixed in `lib0@0.2.72`. Could you please check?
> 
> The recommended way to import/require lib0 is to do `require(lib0/logging)` / `import * as l from 'lib0/logging'`. This should work if you are using `node@>=14`.

Thank you!!!
