### ISSUE TITLE
Possible infinite loop

### ISSUE THREAD

**Issue by YousefED** [yjs/yjs#516]
I'm applying an invalid update:

<img width="255" alt="image" src="https://user-images.githubusercontent.com/368857/228932198-d6467773-1176-4858-80df-5c43f16c7b25.png">

This causes the following call stack:

<img width="457" alt="image" src="https://user-images.githubusercontent.com/368857/228932342-2bc341ac-a8c2-4c5a-a437-b1a8b1ccd1e7.png">

which will then cause an infinite loop in `readVarUint`

This has the potential to break clients, but also servers (for example, if I send a malicious update to Hocuspocus or similar)

**Comment by dmonad** [comment]
Please fill out the form. Nothing in this ticket is actionable for me.

**Comment by dmonad** [comment]
I actually think that this was fixed a while back. Please open a new ticket if you can come up with steps to reproduce in the latest version.

**Comment by YousefED** [comment]
Apologies, filed this too rushed indeed. Seems like relevant code was changed indeed and should have tested that. Will report back in case I notice it again!

Best,
