### ISSUE TITLE
Shared types in XmlText/XmlElement attributes after applyUpdates

### ISSUE THREAD

**Issue by SamyPesse** [yjs/yjs#527]
**Describe the bug**

I don't know if it's a bug or "by-design": it looks like using shared types in `XmlText`/`XmlElement` attributes is unreliable. It works in the main document, but not when applied to a remote document.

**To Reproduce**

You can reproduce it using the following snippet (for example in https://npm.runkit.com/yjs):

```js
var yjs = require("yjs")

const a = new yjs.Doc();
const aText = a.get('text', yjs.XmlText)

const map = new yjs.Map()
map.set('prop', 'something');

aText.insert(0, 'Hello world', {
  testAttribute: map
});


const aDeltas = aText.toDelta();
console.log(aDeltas[0].attributes['testAttribute'])

const b = new yjs.Doc();

const update = yjs.encodeStateAsUpdate(a);
yjs.applyUpdate(b, update);

const bText = b.get('text', yjs.XmlText)
const bDeltas = bText.toDelta();
console.log(bDeltas[0].attributes['testAttribute'])
```

It logs `YMap` and then `{}`.

**Expected behavior**

Shared types can be used as attributes in XML elements.

**Additional context**

Tested using version 13.5.45

**Comment by dmonad** [comment]
Hi @SamyPesse,

Yjs currently does not support nesting Yjs types in JSON objects. See also #255.

#255 is a blocker for supporting nesting of Yjs types in formatting attributes. Even then, it might be unfeasible to support this feature. The nature of formatting attributes would make it very difficult to implement this feature. I suggest that you come up with a different solution if that is even necessary. You could, for example, use a GUID-string as a reference instead and store the Yjs type somewhere else.

I'm gonna close this ticket. We can maybe reopen it once #255 is implemented (there is currently no timeline for when this might be finished).

**Comment by SamyPesse** [comment]
Thank you, @dmonad ! 

It makes sense, and we've already implemented a workaround using only `Y.Map`/ `Y.Array` / `Y.XmlText` :)

I was expecting Y.js to not support nesting Yjs types in JSON objects, but I was not expecting that the `Y.XmlText`/`Y.XmlElement` attributes would be considered pure JSON objects, but thought that Yjs was using a `Y.Map` internally to store the attributes.

Do you think `Y.XmlText`/`Y.XmlElement` should be able to store complex attributes (nested Yjs types, etc)? or do you envision `Y.XmlText`/`Y.XmlElement` to closely mirror what XML/HTML DOMs can store (primitives attributes)?

**Comment by dmonad** [comment]
There's a bijective mapping from JSON to Yjs types. However, Yjs does not transform JSON objects to Yjs types automatically. Instead, Yjs encodes (potentially huge) JSON objects using lib0's "Any encoding" that compresses JSON objects efficiently.

> Do you think Y.XmlText/Y.XmlElement should be able to store complex attributes (nested Yjs types, etc)? or do you envision Y.XmlText/Y.XmlElement to closely mirror what XML/HTML DOMs can store (primitives attributes)?

I don't want to give a general recommendation on how to use Yjs types. It really depends on the use-case.  Be creative with Y.Xml*.  Storing Yjs types as attributes (`yxml.setAttribute`) is fully supported (formatting attributes can only be JSON objects).
