### ISSUE TITLE
Type for XmlElement.setAttribute is incorrect

### ISSUE THREAD

**Issue by SamyPesse** [yjs/yjs#531]
**Describe the bug**

The typing for `XmlElement.setAttribute` indicates that it can only accept a string value (https://github.com/yjs/yjs/blob/main/src/types/YXmlElement.js#L137). But according to our chat and https://github.com/yjs/yjs/issues/527#issuecomment-1519108898, it is fully supported to use shared types as attributes.

At the moment, it forces us into adding `@ts-ignore` :)

**Expected behavior**

Typing, as a form of documentation, represents what can be stored as an attribute.

**Comment by dmonad** [comment]
I just published Yjs@13.6.1 with better typings. Now you can do ..

```typescript
// keys can be either string or type
const yxml = new Y.XmlElement<{ [k:string]: Y.Map|string }>()
yxml.get('ymap') // => Y.Map | string | undefined
// for convenience, if you already know some types
const yxml2 = new Y.XmlElement<{ ymap: Y.Map, name: string, [k:string]: any }>()
yxml2.get('ymap') // => Y.Map | undefined
yxml2.get('name') // => string | undefined
```

For backwards compatibility I need to keep the default `{ [k:string]: string }`. But now you can change it.
