### ISSUE TITLE
Inconsistent results from two individual runs.

### ISSUE THREAD

**Issue by LiuZhenyan-Wuzhong** [yjs/yjs#535]
> Please save me some time and use the following template. In 90% of all issues I can't reproduce the problem because I don't know what exactly you are doing, in which environment, or which y-* version is responsible. Just use the following template even if you think the problem is obvious.

**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
Inconsistent results from two individual runs.

**To Reproduce**
1. Open a new dir and initialize a npm project.
2. Install yjs by npm.
`npm i yjs`
3. Make a .mjs file and write following code.
```
import * as Y from 'yjs';

const doc1 = new Y.Doc();
const doc2 = new Y.Doc();

async function sleep(delay) {
  return await new Promise((resolve) => {
    setTimeout(() => {
      resolve();
    }, delay);
  });
}

async function main() {
  // doc1初始化ymap
  doc1.getMap('ymap').set('name', 'wuzhong');
  doc1.getMap('ymap').set('age', 25);

  await sleep(100);

  // doc2更改ymap，但是此步没有同步到doc1
  doc2.getMap('ymap').set('name', 'kebu');

  await sleep(100);

  // doc1更改ymap，但是此步没有同步到doc2
  doc1.getMap('ymap').set('age', 30);

  await sleep(100);

  Y.applyUpdate(doc1, Y.encodeStateAsUpdate(doc2));

  console.log(doc1.getMap('ymap').get('name'));
  console.log(doc1.getMap('ymap').get('age'));

  Y.applyUpdate(doc2, Y.encodeStateAsUpdate(doc1));

  console.log(doc2.getMap('ymap').get('name'));
  console.log(doc2.getMap('ymap').get('age'));
}

main();

```
4. Run the file by nodejs(mine is node18.12.0), maybe you can see two kinds of results.
```
wuzhong
30
wuzhong
30
```
or 
```
kebu
30
kebu
30
```

**Expected behavior**
I think I have change the map in a specific order so I expect the result is 
```
kebu
30
kebu
30
```
The result of doc1 and doc2 are the same, that's good.

**Screenshots**
![image](https://github.com/yjs/yjs/assets/56421773/f92914d6-3a01-4bf5-9b0d-a3b98a0f4a40)

**Environment Information**
 - Node.js(18.12.0)
 - yjs@13.6.1

**Additional context**
Yjs is cool.

**Comment by dmonad** [comment]
Hi @LiuZhenyan-Wuzhong ,

Merges are "random" but always consistent (there will never be two peers with different values). A `clientid` determines which value "wins" the merge. This clientid is automatically generated and shouldn't be changed.

**Comment by LiuZhenyan-Wuzhong** [comment]
Thanks for your response. I know it now.
