### ISSUE TITLE
Crash when .set with the same value

### ISSUE THREAD

**Issue by SamyPesse** [yjs/yjs#551]
**Describe the bug**

Calling `map.set` with the same value already set (or maybe because it's a value already linked ot the document) crashes with `TypeError: Cannot read properties of null (reading 'length')`.

**To Reproduce**

The following code reproduces the error:

```js
const yjs = require("yjs")
const doc = new yjs.Doc();
const map = doc.getMap();
const array = new yjs.Array([1,2,3]);

map.set('value', array);

// This one crashes:
map.set('value', array);
```

**Expected behavior**

It should do nothing :)

**Environment Information**
 - Yjs version: 13.6.6

**Comment by himself65** [comment]
same as https://github.com/yjs/yjs/issues/458#issuecomment-1224800219

> A shared type can only exist once in a document.
