### ISSUE TITLE
Inconsistant output when updating same key in quick-start example

### ISSUE THREAD

**Issue by BenjaminGirard** [yjs/yjs#573]
**Describe the bug**
The basic example in the [quick-start](https://docs.yjs.dev/#quick-start) won't give consistant results if we're trying to update the same key in both documents

**To Reproduce**

execute the following code (exact same as quick-start but the key updated is the same) multiple times:

```
import * as Y from 'yjs'

// Yjs documents are collections of
// shared objects that sync automatically.
const ydoc = new Y.Doc()
// Define a shared Y.Map instance
const ymap = ydoc.getMap()
ymap.set('keyA', 'valueA')

// Create another Yjs document (simulating a remote user)
// and create some conflicting changes
const ydocRemote = new Y.Doc()
const ymapRemote = ydocRemote.getMap()
ymapRemote.set('keyA', 'valueB')

// Merge changes from remote
const update = Y.encodeStateAsUpdate(ydocRemote)
Y.applyUpdate(ydoc, update)

// Observe that the changes have merged
console.log(ymap.toJSON()) // => { keyA: 'valueB' }
```

**Expected behavior**
The expected output should always be the last written update (since the code is executed synchronously) -> `{ keyA: 'valueB' }`

**Screenshots**
<img width="369" alt="image" src="https://github.com/yjs/yjs/assets/20395444/4085fc34-a224-4698-bd6e-5561e4f59011">

**Environment Information**
 -  Node.js 
 - "yjs": "^13.6.7"

**Comment by himself65** [comment]
I believe this is expected behavior. CRDT won't guarantee that the result is always correct for each round, it only guarantees the result is the same for every client.

In your case, this could be because `clientId` is different for each round, and might bigger or smaller client will win the result and overwrite the data.
