### ISSUE TITLE
Allow to overwrite the clientID generation function in a YDoc

### ISSUE THREAD

**Issue by nikgraf** [yjs/yjs#574]
**Checklist**

**Is your feature request related to a problem? Please describe.**

I would love to have more control over the clientID. Specifically to map it to clients which are identified by an user/client/device ID or public key.
In absolute best case the clientID wouldn't need to be a number, but that might be a larger Yjs change that might now align with your goals.

https://github.com/serenity-kit/secsync/pull/47/files#diff-67ee2fa5083c3f06bace9b0918a52efdb1e2069c17fb0086121dd74e6226f964

**Describe the solution you'd like**

In my case I take the first 32 bits from the publicKey of the client and the next 21 are randomised.
https://github.com/serenity-kit/secsync/pull/47/files#diff-67ee2fa5083c3f06bace9b0918a52efdb1e2069c17fb0086121dd74e6226f964

I do this right after instantiating the YDoc, but in case of a collision Yjs chooses another ID and my matching of the public key would fail.
https://github.com/serenity-kit/secsync/pull/47/files#diff-41155ef9b3b46eabaa17e0af55383cbe3cb2f008205527b2e4fdf8ef1759ed59R50-R53

Ideally I could provide a function like `generateClientId` to the YDoc itself so it can create another ID with my algorithm. 

**Describe alternatives you've considered**

Listening to changes and as soon as the wrong clientID comes in I could try to undo the change, set the cliendID and reapply the change? Haven't really thought this through or tried it yet.

**Comment by nikgraf** [comment]
@dmonad I would open a PR, but would not start before you have the feeling this is a useful addition :)

**Comment by himself65** [comment]
Same as https://github.com/yjs/yjs/issues/519

**Comment by nikgraf** [comment]
Thanks for the hin @himself65 👏
