### ISSUE TITLE
RangeError Invalid typed array length: 110 & TypeError: contentRefs[(info & binary.BITS5)] is not a function

### ISSUE THREAD

**Issue by danielblignaut** [yjs/yjs#599]
> Please save me some time and use the following template. In 90% of all issues I can't reproduce the problem because I don't know what exactly you are doing, in which environment, or which y-* version is responsible. Just use the following template even if you think the problem is obvious.

**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**

Our Sentry instance is intermittently receiving this RangeError ->

```
<anonymous> in new Uint8Array
/node_modules/yjs/node_modules/lib0/buffer.js in Module.createUint8ArrayViewFromArrayBuffer at line 24:84
/node_modules/yjs/node_modules/lib0/decoding.js in readUint8Array at line 104:23
/node_modules/yjs/node_modules/lib0/decoding.js in Module.readVarUint8Array at line 119:45
/node_modules/yjs/dist/yjs.mjs in UpdateDecoderV1.readBuf at line 794:43
/node_modules/yjs/dist/yjs.mjs in Array.readContentBinary at line 8432:64
/node_modules/yjs/dist/yjs.mjs in readItemContent at line 10014:76
/node_modules/yjs/dist/yjs.mjs in readClientsStructRefs at line 1400:13
/node_modules/yjs/dist/yjs.mjs in <anonymous> at line 1627:16
/node_modules/yjs/dist/yjs.mjs in transact at line 3354:14
/node_modules/yjs/dist/yjs.mjs in readUpdateV2 at line 1620:3
/node_modules/yjs/dist/yjs.mjs in applyUpdateV2 at line 1715:3
/node_modules/yjs/dist/yjs.mjs in applyUpdate at line 1729:58
```
For context, in our code, we have code around this exception like so:

```typescript
const documentRes = await fetch(`https://${env('NEXT_PUBLIC_TIPTAP_APP_ID')}.collab.tiptap.cloud/api/documents/${documentId}?format=yjs`, {
    method: 'get',
    headers: {
      Authorization: env('TIPTAP_API_SECRET'),
    },
  })

  const buffer = await documentRes.arrayBuffer()
  const initialYDocUpdate = new Uint8Array(buffer);

const ydoc = new Doc()
applyUpdate(ydoc, initialYDocument); #this line throws the exception
```

Following the stack trace, the problematic line seems to come from the underlying lib0 library:

```javascript

/**
 * Create Uint8Array with initial content from buffer
 *
 * @param {ArrayBuffer} buffer
 * @param {number} byteOffset
 * @param {number} length
 */
//This line is the origin of the error
export const createUint8ArrayViewFromArrayBuffer = (buffer, byteOffset, length) => new Uint8Array(buffer, byteOffset, length)
/**
 * Create Uint8Array with initial content from buffer
 *
 * @param {ArrayBuffer} buffer
 */

```

I'm unfamiliar with the restrictions around Uint8Arrays but I suspect there's one of 2 things going wrong:
1. we are receiving a bad response from TipTap for the initial Uin8Array
2. I am mishandling the response from TipTap when applying the update (there's perhaps an issue in how I'm converting the ArrayBuffer to an Uint8Array
3. There's a bug in lib0 or Yjs code causing this issue

**To Reproduce**

Unfortunately I can't reproduce the issue, it seems to happen intermittently and I am not receiving any bad responses from TipTap Although ArrayBuffers / Uint8Arrays are not very human readable in the first place.

Have you seen an issue like this before?

**Expected behavior**

**Screenshots**

**Environment Information**
- Node.JS
- @hocuspocus/provider@2.7.1
- yjs@13.6.8

**Additional context**

**Comment by dmonad** [comment]
Hi @danielblignaut ,

This doesn't look like a Yjs issue. Please open a ticket at the hocuspocus/tiptap organization.  

I receive a lot of throughput from this company that makes a lot of money on top of my software (which is fine), but I don't want to help them without compensation. If you use their software, you should target their issue tracker first - thanks!
