### ISSUE TITLE
y-loopback

### ISSUE THREAD

**Issue by idevelop** [yjs/yjs#610]
Hey folks, I'm working on a feature that I'm approaching by "simulating" a second collaborator on a document. The data of what changes this second entity (an LLM) makes to the document are provided to me from a separate event stream incompatible with yjs. I was planning to connect the two collaborators together through some kind of `y-loopback` provider, which would have nothing to do with the network and just passes sync messages locally between each document's respective provider instances. I was imagining you'd already have something like this for local manual / unit testing at least?

I haven't found anything that looks like that in the yjs library ecosystem, which probably means one of two things:
1. I'm thinking about this the wrong way and I should do something else instead
2. It sounds useful, it's just that no-one has built this yet

If it's the latter, I'd love to take a stab at it, if you could just point to me to any relevant documentation.

Thanks!

**Comment by dmonad** [comment]
Providers sync Yjs documents with the network or some database.

Sounds like you want to implement a binding: When the "LLM" makes a change, you want to update the Yjs document (via, for example the `text.insert` method). No provider is really necessary.

This LLM can live on a separate machine or thread, you can connect it to other clients using a provider.

**Comment by dmonad** [comment]
Providers sync Yjs documents with the network or some database.

Sounds like you want to implement a binding: When the "LLM" makes a change, you want to update the Yjs document (via, for example the `text.insert` method). 

This LLM can live on a separate machine or thread, you just need to connect it to other clients using a provider.

**Comment by idevelop** [comment]
Thanks for the steer @dmonad, hadn't thought of that!

IIUC the main change with that approach is that instead of applying the changes from the LLM onto the text editor (in my case Tiptap) and relying on its Collaboration extension to turn those into yjs mutations, I'd be taking responsibility for mutating the yjs document myself. I think I need to study both APIs a bit more before I can judge which maps more to how the LLM deltas are represented.
