### ISSUE TITLE
UndoManager stack cleared after a removal on remote side

### ISSUE THREAD

**Issue by guigui64** [yjs/yjs#615]
**Describe the bug**
UndoManager stack seems to be cleared when remote removes an element in an array of a Y.Map entry.

**To Reproduce**
1. Go to '[this devbox](https://codesandbox.io/p/devbox/8p4h5f?file=%2Fsrc%2FApp.tsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsyuzqgg00063b6hofe8jonz%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsyuzqgg00023b6h3ffzshye%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsyuzqgg00033b6h84bw0ufa%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsyuzqgg00053b6h57sm1n43%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsyx14j001cs3b6iaf4vlrni%2522%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsyuzqgg00023b6h3ffzshye%2522%253A%257B%2522id%2522%253A%2522clsyuzqgg00023b6h3ffzshye%2522%252C%2522activeTabId%2522%253A%2522clt1lli8l00023b6i7las4uuu%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clsywkpuc00u83b6is5q7gv4p%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clt1lli8l00023b6i7las4uuu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clsyuzqgg00053b6h57sm1n43%2522%253A%257B%2522id%2522%253A%2522clsyuzqgg00053b6h57sm1n43%2522%252C%2522activeTabId%2522%253A%2522clsywewpr008j3b6iltxlodd9%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clsywewpr008j3b6iltxlodd9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clsyuzqgg00033b6h84bw0ufa%2522%253A%257B%2522id%2522%253A%2522clsyuzqgg00033b6h84bw0ufa%2522%252C%2522activeTabId%2522%253A%2522clsywetml006f3b6ijpaw5kmn%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clsywetml006f3b6ijpaw5kmn%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522clsywgd0u00hc3b6iwt1db94i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clsywgd56000rdjeh6g062gqc%2522%257D%255D%257D%252C%2522clsyx14j001cs3b6iaf4vlrni%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsywozdy016d3b6it2xx8jgg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsyx14j001cs3b6iaf4vlrni%2522%252C%2522activeTabId%2522%253A%2522clsywozdy016d3b6it2xx8jgg%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)'
2. On one instance, do some stuff (like toggling todos for instance)
3. On the other instance, remove one todo
4. Undo on the first instance has no effect

**Expected behavior**
Undo on the first instance should undo the actions taken at step 2.

**Screenshots**

**Environment Information**
```
"immer-yjs": "1.1.1",
"y-webrtc": "10.3.0",
"yjs": "13.6.12"
```

**Additional context**

**Comment by dmonad** [comment]
I think you will be able to debug this yourself. 

Please first implement your app first using Yjs types (using `insert` & `delete` methods on `Y.Array`). Then you can try moving to an abstraction layer like immer. This is definitely a bug on your end.
