### ISSUE TITLE
docs: duplicate Y.Event page entry

### ISSUE THREAD

**Issue by MentalGear** [yjs/yjs#616]
Really looking forward to the new docs (especially dark mode!). I noticed in the beta, that Y.Event has duplicate pages, with the almost same content.
https://beta.yjs.dev/docs/api/y.event <--- this seems the outdated version
https://beta.yjs.dev/docs/api/shared-types/y.event

**Comment by dmonad** [comment]
Hi thanks for the hint! But there are so many things that I want to change on the new documentation website, that I'm gonna close this issue. The documentation is quite hard to maintain, so the next iteration will generate the docs directly from the sourcecode, which should resolve this issue anyway.
