### ISSUE TITLE
Impossible to save a Y.Map when deleted from a Y.Array

### ISSUE THREAD

**Issue by guigui64** [yjs/yjs#622]
**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
I have a `Y.Array` of `Y.Map`s (`Y.Array<Y.Map<number>>`). I want to be able to save an element of the array before deleting it from the array so that I can insert it into another array later.
However, after the call to delete, the save is empty. I also tried using `clone` but I cannot figure out how it works because the clone is always empty.

**To Reproduce**
```
import * as Y from "yjs";

const doc = new Y.Doc();
const array = doc.getArray("array");

const m1 = new Y.Map();
m1.set("id", 1);
const m2 = new Y.Map();
m2.set("id", 2);
array.push([m1, m2]);
console.log("array", array.toJSON()); // prints [ { id: 1 }, { id: 2 } ] as expected

const first = array.get(0) as Y.Map<number>;
const clone = first.clone();
console.log("first", first.toJSON()); // prints { id: 1 } as expected
console.log("clone", clone.toJSON()); // prints {}
array.delete(0, 1);
console.log("array", array.toJSON()); // prints [ { id: 2 } ] as expected
console.log("first", first.toJSON()); // prints {} ===> save is lost
console.log("clone", clone.toJSON()); // prints {}

```

**Expected behavior**
I expect the save to keep the content of my `m1` map.

**Comment by dmonad** [comment]
You can only use types after they have been included somewhere in the ydoc. One you do `array.push([clone])` the data should not be empty anymore. I added a comment to the method as a clarification.

**Comment by guigui64** [comment]
Thanks for the quick reply!
Can you also explain why I get this error if rather than doing `array.push([clone])` as you mentioned I do `array.push([first])`:

```
5969 |     ;/** @type {Map<string, any>} */ (this._prelimContent).forEach((value, key) => {
                                             ^
TypeError: null is not an object (evaluating 'this._prelimContent.forEach')
```

**Comment by dmonad** [comment]
You can't integrate a shared type twice into a document.

**Comment by dmonad** [comment]
`first` was already integrated. so you can't integrate it again.
