### ISSUE TITLE
Global document undo manager

### ISSUE THREAD

**Issue by davidbrochart** [yjs/yjs#623]
It seems that a `Y.UndoManager` is always scoped to some shared types. In my case I have a document for which I don't know the structure, I just want to revert it to a previous state. For that it would be nice to have the undo manager scoped globally to the document. Is it possible?
Is there another way, not involving an undo manager, to revert a document to a previous state?

**Comment by dmonad** [comment]
I answered this one already in the discussion forum...

**Comment by davidbrochart** [comment]
Yes, thanks! Here is the [link](https://discuss.yjs.dev/t/global-document-undo-manager/2555/2).
