### ISSUE TITLE
Delta embeds support

### ISSUE THREAD

**Issue by volser** [yjs/yjs#631]
**Checklist**

[ ] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
[ ] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Is your feature request related to a problem? Please describe.**
In version 5.0 of Delta lib was added `Delta.registerEmbed()` for OT support for embeds.

how it works in Delta:
https://github.com/quilljs/delta/blob/dc17ca03e1d68ee729c8cd1ff790ebf96eb0fbec/test/delta/compose.ts#L236

How it works with YJS?

This feature is used for Table support in Quill

**Describe the solution you'd like**
Need to add YJS support for such structures as well

**Comment by dmonad** [comment]
The delta format supports embeds. YText supports the delta format.

There is also a method `ytext.insertEmbed(pos, embedObject)`

**Comment by volser** [comment]
@dmonad sorry but I meant not nested Object, but nested Delta
https://github.com/slab/delta/pull/77

It's a breaking change to Delta format. New Quill Table module uses this feature
https://github.com/slab/quill/blob/main/packages/quill/src/modules/tableEmbed.ts
