### ISSUE TITLE
Regression in v13.6.13 and up

### ISSUE THREAD

**Issue by rustysys-dev** [yjs/yjs#632]
**Describe the bug**
https://discuss.yjs.dev/t/breaking-change-introduced-in-v13-6-13/2599

The changes to the Doc Type breaks builds in code which was making use of the ability to create custom events on the doc. 

**To Reproduce**
1. Create an instance of doc
2. Create an on.('non-defined-event', ...)
3. Attempt to emit that event
4. The typescript compiler throws an error.

**Expected behavior**
we are able to create custom events 

**Screenshots**
![image](https://github.com/yjs/yjs/assets/34673206/804f4546-28ff-4424-be5f-da1cee2fc741)

**Environment Information**
 - nodejs ^18
 - yjs v13.6.13, yjs v13.6.14

**Comment by dmonad** [comment]
I'm sorry that this breaks your existing codebase. However, I don't want to revert to an untyped event system.
There is a big advantage in having typed events.

The only way I see to "fix" this is to allow user-defined events that you can define on Yjs using typescript. E.g. `new Y.Doc<{ error: ErrorObject => void }>()`

However, I also don't want to do that. There is a good chance that I eventually want to define the "error" event in Yjs. Now, if I allow custom events, then I would break everyone's codebase whenever I add a new event. This would lock me in, making me unable to add custom events on the data type I maintain, while only allowing users to add new event types.

I also dislike it when it's not clearly defined who owns something (e.g., is the error event fired by you or by me?).

I didn't intend for users of Yjs to fire their own events using the Yjs object. Now, with the type event system it is made clear that this is not possible. 

Therefore, I see the burden on you to build your own event system - possibly by wrapping Yjs in a custom datatype. I'm sorry, this is probably not what you wanted to hear.

**Comment by rustysys-dev** [comment]
@dmonad no problem at all, and the direction is understandable. I mainly only pointed it out because it happened in a patch version. Otherwise I wouldn't have. 

Thanks for all your hard work on this project!!
