### ISSUE TITLE
Allow subscribing to only updates with a specific origin on doc.on('update', () => {}) 

### ISSUE THREAD

**Issue by walfly** [yjs/yjs#634]
**Is your feature request related to a problem? Please describe.**
I'm trying to build a history of the document that includes snapshots that are created only when specific fields are changed locally. I want to batch these snapshots so that they don't include single character changes.  Currently I'm achieving this by storing all updates with a debounce that collects all calls between executions and then filtering by origin.
```ts
const updateHandler = curriedDebounce((updates: any) => {
        const relevantUpdates = updates.filter((updateArgs: any[]) => {
            updateArgs[1] === 'relevantLocalChange';
        }).map((updateArgs) => updateArgs[0]);
 }
```

These has several drawbacks when multiple people are editing simultaneously.  It would be better if I could subscribe only to relevant updates.

**Describe the solution you'd like**
I'd like to be able to create an update listener like this `doc.on('update:relevantLocalChange', () => {})` and have it only fire when an update has that origin.  Or be able to pass the origin as a separate param like  `doc.on('update', () => {}, 'relevantLocalChange')`.

**Describe alternatives you've considered**
I'm currently doing the filtering inside the update handler but this has some drawbacks. 

**Additional context**

**Comment by walfly** [comment]
I'm happy to take this work on with guidance on an acceptable api for the feature.

**Comment by dmonad** [comment]
You can probably implement this yourself by doing:

```js
const updateCache = []
ydoc.on((update, origin) => {
  if (origin === 'relevant origin') {
    updateCache.push(update)
    debounce(() => {
      send(updateCache)
      updateCache.length = 0
    })
  }
})
```

Even if there are use cases for this specific implementation, it is not general enough to be included in this project. 99% of users won't need this feature. Also, it can be safely implemented by you.
