### ISSUE TITLE
yjs v13.6.13 breaks `y-utility/y-multidoc-undomanager`

### ISSUE THREAD

**Issue by acnebs** [yjs/yjs#645]
**Describe the bug**
Changes made in yjs v13.6.13 break the YMultiDocUndoManager found in [y-utility](https://github.com/yjs/y-utility).

I haven't had time to look through the code of each to identify the cause more directly, but wanted to go ahead and make sure this issue was known.

**To Reproduce**
1. Install yjs > 13.6.12
2. Install and use latest YMultiDocUndoManager
3. Trigger an undo from YMultiDocUndoManager
4. The entire undo stack is undone and wiped, not the last stack item

**Expected behavior**
Triggering `YMultiDocUndoManager.undo` should undo a single stack item, not the entire stack.

**Environment Information**
 - yjs v13.6.13
 - y-utility v0.1.4

**Comment by furkan3ayraktar** [comment]
We noticed the same issue on yjs version 13.6.16
