### ISSUE TITLE
Cannot undo a change made from y-crdt in Yjs

### ISSUE THREAD

**Issue by davidbrochart** [yjs/yjs#647]
**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [ ] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
I have a setup where a Doc is shared between a `y-crdt` and a `Yjs` peer through a WebSocket, and it seems that a change made on the `y-crdt` side cannot be undone on the `Yjs` side. Before sharing more details (and maybe a reproducible example), could you confirm that this is possible?

cc @dmonad @Horusiath

**Comment by dmonad** [comment]
Usually, remote changes are not tracked by `Y.UndoManager`. 

But if you configured it to track remote changes:
Is this issue really specific to Y-CRDT as a remote client?

**Comment by davidbrochart** [comment]
How can I configure it to track remote changes?

**Comment by davidbrochart** [comment]
I saw the undo manager `ignoreRemoteMapChanges: true` option, but it doesn't have any effect.
Basically this is what I am trying to do:
```js
const Y = require('yjs')

const doc0 = new Y.Doc()
const doc1 = new Y.Doc()

doc0.on('update', update => {
  Y.applyUpdate(doc1, update)
})

doc1.on('update', update => {
  Y.applyUpdate(doc0, update)
})

const map0 = doc0.getMap('map')
const map1 = doc1.getMap('map')

const undoManager = new Y.UndoManager(map1)

map0.set('key0', 'val0')
console.log(map1.toJSON())

undoManager.undo()
console.log(map1.toJSON())
```
Which works fine, because it prints:
```
{ key0: 'val0' }
{}
```
The undo manager did undo the remote change.
So it seems that the issue is specific `y-crdt` as a remote client.

**Comment by dmonad** [comment]
I don't think so. If you use y-websocket, you need to add the y-websocket provider instance as a tracked origin. Then it should work fine. 

Yjs & Y-CRDT should always generate the same updates. Since this is a basic case, I don't expect that they generate different updates that would result in an issue.

**Comment by davidbrochart** [comment]
> If you use y-websocket, you need to add the y-websocket provider instance as a tracked origin.

Thanks, that worked. But is it documented somewhere?

**Comment by dmonad** [comment]
https://docs.yjs.dev/api/undo-manager

> Optionally, you may specify trackedOrigins to filter specific changes. By default, all local changes will be tracked.

I updated it to:

>  Optionally, you may specify trackedOrigins to track changes from different sources. By default, all local changes that don't specify an origin will be tracked.

Feel free to contribute to the docs. I think it already explains how origins can be used.

**Comment by davidbrochart** [comment]
That part was fine, but I think there should be a mention that `y-websocket` adds the WebSocket provider as an origin to the changes (that was the information I was missing).
