### ISSUE TITLE
Inconsistency when creating absolute position from a relative position

### ISSUE THREAD

**Issue by JuanM04** [yjs/yjs#657]
**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
Following what has been discussed in https://github.com/yjs/yjs/issues/638, the absolute position index obtained from `Y.createAbsolutePositionFromRelativePosition` differs from `followUndoneDeletions=true` to `followUndoneDeletions=false`. This is expected when applying undo/redo operations, but not when those don't occur.

**To Reproduce**
[StackBlitz reproduction](https://stackblitz.com/edit/vitest-dev-vitest-gifybb?file=test%2Fyjs.test.ts)

1. Create a `Y.Text`.
2. Insert some text. For example, `abcde`.
3. Create a relative position. For example, one that points to the index 2.
4. Immediately, get the absolute position from that relative one with `followUndoneDeletions=true`.

**Expected behavior**
Without even an UndoManager attached, the absolute position should point to the original position (in the example, 2). Instead, it points to another place (in the example, 0).

**Environment Information**
 - Yjs version 13.6.18

* [ ] I'm a sponsor 💖
* [x] This issue is a blocker for my project.

**Comment by dmonad** [comment]
Thanks for reporting the issue!

This is fixed in `yjs@13.6.21`
