### ISSUE TITLE
在vue2中引入报错

### ISSUE THREAD

**Issue by qq707631575** [yjs/yjs#661]
在vue2框架中引入
 import * as Y from 'yjs'
报错：

in ./node_modules/yjs/dist/yjs.mjs

Can't import the named export 'BOLD' from non EcmaScript module (only default export is available)

 error  in ./node_modules/yjs/dist/yjs.mjs

Can't import the named export 'ORANGE' from non EcmaScript module (only default export is available)

 error  in ./node_modules/yjs/dist/yjs.mjs

Can't import the named export 'RED' from non EcmaScript module (only default export is available)

 error  in ./node_modules/yjs/dist/yjs.mjs

Can't import the named export 'UNBOLD' from non EcmaScript module (only default export is available)

 error  in ./node_modules/yjs/dist/yjs.mjs

Can't import the named export 'print' from non EcmaScript module (only default export is available)

 error  in ./node_modules/yjs/dist/yjs.mjs

Can't import the named export 'warn' from non EcmaScript module (only default export is available)

 error  in ./node_modules/lib0/logging.js

Module parse failed: Unexpected token (40:35)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

**Comment by dmonad** [comment]
I can't act on this

**Comment by qq707631575** [comment]
> I can't act on this

vue2.0 + vue-cli4 + yjs
