### ISSUE TITLE
`Y.diffUpdate` does not properly diff out deletions (but does diff out insertions) in `Y.Text`

### ISSUE THREAD

**Issue by acnebs** [yjs/yjs#663]
**Describe the bug**
I am trying to use the `Y.diffUpdate` API in order to take a set of changes and remove some of them, as a sort of "undo" action on a `Y.Text`. This works fine for insertion operations, but for some reason is not working for deletion operations. As far as I can tell I am not doing anything wrong, so I think this is a bug.

**To Reproduce**
```ts
import * as Y from 'yjs';

const origDoc = new Y.Doc();
origDoc.getText('myText').insert(0, 'I have some text');
const baseUpdate = Y.encodeStateAsUpdate(origDoc);

const storedUpdates: Uint8Array[] = [];

// kept
const keptChangesDoc = new Y.Doc();
Y.applyUpdate(keptChangesDoc, baseUpdate);
keptChangesDoc.on('update', (update: Uint8Array) => storedUpdates.push(update));
const keptChangesText = keptChangesDoc.getText('myText');
keptChangesText.insert(keptChangesText.length, ' in here');
const keptUpdate = Y.encodeStateAsUpdate(keptChangesDoc);

console.log(keptChangesText.toString());

// undoable
const undoableDoc = new Y.Doc();
Y.applyUpdate(undoableDoc, baseUpdate);
Y.applyUpdate(undoableDoc, keptUpdate);
const undoableUpdates: Uint8Array[] = [];
undoableDoc.on('update', (update) => {
    storedUpdates.push(update);
    undoableUpdates.push(update);
});
const undoableText = undoableDoc.getText('myText');
undoableText.delete(0, 7);
undoableText.insert(0, "Now ")

console.log(undoableText.toString());

// merge updates
const mergedStoredUpdate = Y.mergeUpdates(storedUpdates);
const mergedUndoableUpdate = Y.mergeUpdates(undoableUpdates);

// remove "undoable" updates
const deltaUpdate = Y.diffUpdate(mergedStoredUpdate, Y.encodeStateVectorFromUpdate(mergedUndoableUpdate));
// at this point, deltaUpdate *should* have only the changes from keptUpdate but it does not, 
// the "undoable" deletion action is still around, but the insertion action has been removed
console.log(Y.decodeUpdate(deltaUpdate));

// final document
const finalDoc = new Y.Doc();
Y.applyUpdate(finalDoc, baseUpdate);
Y.applyUpdate(finalDoc, deltaUpdate);
// should read "I have some text in here"
console.log(finalDoc.getText('myText').toString());
// but actually reads "some text in here"
```

**Expected behavior**
When using `Y.diffUpdates`, all types of operations should be diffed, including deletions.

**Environment Information**
- latest YJs, all runtimes

* [x] This issue is a blocker for my project.

**Comment by acnebs** [comment]
I dug into the code-base a bit, and it seems like this is somewhat deliberate. The `diffUpdatesV2` function diffs insertions, but then [just copies over the `DeleteSet` from the update](https://github.com/yjs/yjs/blob/f2ff8b95367250b8d080db0c98940997de1bc986/src/utils/updates.js#L497). Is there a technical or practical reason it was done this way? Because it seems counter-intuitive / undesirable to have this be the behavior.

For example `mergeUpdatesV2` [actually performs a merge](https://github.com/yjs/yjs/blob/f2ff8b95367250b8d080db0c98940997de1bc986/src/utils/updates.js#L456C14-L456C29) on the `DeleteSet`s, so I'd `diffUpdateV2` to behavior similarly and diff all constituent parts of the data structure.

**Comment by dmonad** [comment]
Hi @acnebs ,

This is deliberate. I think you also opened a ticket in the discussion board where I gave an elaborate answer to your question.

When clients initially sync, they should sync the complete delete set. Not keeping track of deletions allows us to do more optimizations later. With run-length encoding, the encoded delete set is usually extremely small, compared to the rest of the document.
