### ISSUE TITLE
Add sanity checks for Yjs caveats

### ISSUE THREAD

**Issue by dmonad** [yjs/yjs#667]
1. Throw an error in `.get()`, `.length`, etc; instead of returning `null/undefined/0`. Returning a value seems to indicate that it can be used, while it should not. An error could help directly identify during development invalid cases.
2. For the JSON copy problem, similar to `recoil`, I think we should do a `if (process.env.NODE_ENV === 'development') { deepFreeze(value) }`

_Originally posted by @SamyPesse in https://github.com/yjs/yjs/issues/666#issuecomment-2378549086_

**Comment by dmonad** [comment]
Done @SamyPesse 

I can't stop returning data. That would be a breaking change. Hence, 1. will simply log a warning.

2) is fully implemented. In dev_mode, objects can't be manipulated anymore. I consider this not a breaking change.

This will be available in the next Yjs release.

**Comment by jpreynat** [comment]
Thanks for this @dmonad 👍 

In the meantime, we were using a custom patched version of Yjs to achieve the same.
Would it be possible to have a release that includes those changes anytime soon?

Thanks again

**Comment by dmonad** [comment]
Sure, done!

-------- Original Message --------

**Comment by jpreynat** [comment]
Thanks a lot!
