### ISSUE TITLE
Lexical Collaboration YJS

### ISSUE THREAD

**Issue by FirasLatrech** [yjs/yjs#670]
I'm working on a project where I’m integrating Lexical Editor with Yjs for real-time collaboration. While I have successfully set up the collaborative editing using Yjs and Lexical, I’m struggling with syncing the Yjs document data to my own database. Specifically, I need to persist the Yjs data to a database (I’m using PostgreSQL/Supabase) and restore it when needed.

My Current Setup:
Lexical editor bound to Yjs document for collaborative editing.
Users send updates to the Yjs server via WebSockets.
I need to persist Yjs document updates from the Yjs server into my own database as JSON, and load it back when required.
Where I’m Stuck:
How do I properly listen for updates on the Yjs document (or Yjs server) and save them to my database?
What’s the best way to restore the document state from the database when initializing the editor?
Are there any best practices or examples for this kind of integration?
I am using Next.js, Prisma, and PostgreSQL in my stack. I would greatly appreciate any guidance or code examples that could help with saving and loading Yjs document data to/from a database.

Thanks so much in advance for any help or suggestions!
![Screenshot 2024-10-18 at 10 44 18](https://github.com/user-attachments/assets/93ca2b8d-24c7-4cc1-9316-dc088fbdb653)

**Comment by dmonad** [comment]
Hi @FirasLatrech ,

This is not the right place to ask questions. Please use discuss.yjs.dev for that. 

The y-websocket docs might actually answer your question. If you want more guidance, I suggest your company books a one-time session with me (https://github.com/sponsors/dmonad?frequency=one-time&sponsor=dmonad).
