### ISSUE TITLE
Required Node.js version?

### ISSUE THREAD

**Issue by LeeQe** [yjs/yjs#672]
Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
What's the required node version used by this project? Thank you~

**Comment by dmonad** [comment]
Any nodejs version that is still being maintained is supported (https://nodejs.org/en/about/previous-releases). Currently, I test anything >=v16. 

Please use the discussion board the next time. This is not the right place to ask questions - which is stated in the issue template!
