### ISSUE TITLE
Problem help

### ISSUE THREAD

**Issue by NameWjp** [yjs/yjs#673]
// Initial status of the remote end
const remoteDoc = new Y.Doc()
const list = remoteDoc.getArray<number>('list')
list.insert(0, [1, 2, 3])
const buffer = Y.encodeStateAsUpdate(remoteDoc)
const remoteVector = Y.encodeStateVector(remoteDoc)

// Client A synchronizes the status and moves 2 before 1
const localA = new Y.Doc()
Y.applyUpdate(localA, buffer)
const listA = localA.getArray('list')
listA.delete(1, 1)
listA.insert(0, [2])
console.log('localA', listA.toArray()); // [2, 1, 3]

// Client B synchronizes the status and moves 2 after 3
const localB = new Y.Doc()
Y.applyUpdate(localB, buffer)
const listB = localB.getArray('list')
listB.delete(1, 1)
listB.insert(2, [2])
console.log('localB', listB.toArray()); // [1, 3, 2]

// The client synchronizes data to the remote end
const updateA = Y.encodeStateAsUpdate(localA, remoteVector)
Y.applyUpdate(remoteDoc, updateA)
const remoteVector2 = Y.encodeStateVector(remoteDoc)
const updateB = Y.encodeStateAsUpdate(localB, remoteVector2)
Y.applyUpdate(remoteDoc, updateB)
console.log('remote', list.toArray()); // [2, 1, 3, 2]

How do I solve the duplicate 2

**Comment by dmonad** [comment]
Please read the issue template. This is not the right place to ask for questions. We have a discussion board.  I want to only keep bug reports here.

Personally, I find your behavior quite disrespectful. I will ban you from this organization when this happens again.

**Comment by NameWjp** [comment]
> Please read the issue template. This is not the right place to ask for questions. We have a discussion board. I want to only keep bug reports here.
> 
> Personally, I find your behavior quite disrespectful. I will ban you from this organization when this happens again.

sorry~
