### ISSUE TITLE
Performance Issues with `applyUpdate` and `encodeStateAsUpdate`

### ISSUE THREAD

**Issue by RubaXa** [yjs/yjs#675]
Hello @dmonad, thank you so much for such an amazing library, it's truly impressive 💪

I am working on yet-another-board-service™️, and at the moment, the workflow with YDoc looks like this:

#### Loading
```ts
async loadDocument(doc: Y.Doc) {
  const state = await getData(`/api/board-state/{uid}`);
  Y.applyUpdate(state, doc);
}
```

#### Saving
```ts
async saveDocument(doc: Y.Doc) {
  const state = Y.encodeStateAsUpdate(doc);
  await postData(`/api/board-state/{uid}`, state);
}
```

Everything was working fine until we noticed freezes, especially for documents larger than 5MB:

```
Size v1: 8969403, v2: 452346
 - applyUpdateV1: 1395.8995413780212
 - applyUpdateV2: 1771.560583114624
 - encodeStateAsUpdateV1: 113.66412496566772
 - encodeStateAsUpdateV2: 251.43258333206177
Size v1: 8969403, v2: 452346
 - applyUpdateV1: 1573.7430000305176
 - applyUpdateV2: 1567.5406670570374
 - encodeStateAsUpdateV1: 110.09554195404053
 - encodeStateAsUpdateV2: 279.0862922668457
Size v1: 8969403, v2: 452346
 - applyUpdateV1: 1544.837124824524
 - applyUpdateV2: 1320.8857498168945
 - encodeStateAsUpdateV1: 113.58862495422363
 - encodeStateAsUpdateV2: 243.61533403396606
```
MacOS / M3
NodeJS v18.20.4

In reality, these numbers can exceed 5-8sec on the server.

It’s possible that my approach to working with YDoc isn’t the best, and there might be a more optimal way. I would be grateful for any help.

<details>
<summary>Here is an example benchmark</summary>

```ts
const { readFileSync } = require('fs');
const { performance } = require('perf_hooks');
const { Doc, applyUpdate, applyUpdateV2, encodeStateAsUpdate, encodeStateAsUpdateV2 } = require('yjs');
const {toUint8Array} = require('js-base64');

const board = JSON.parse(readFileSync('./disco-board.json').toString());

const runTest = () => {
	let ydocState = toUint8Array(board.ydoc);
	const sample = {
		updateV1: null,
		updateV2: null,
		applyUpdateV1: 0,
		applyUpdateV2: 0,
		encodeStateAsUpdateV1: 0,
		encodeStateAsUpdateV2: 0,
	};
	const ydoc = new Doc();
	
	// ApplyV1
	{
		const start = performance.now();
		applyUpdate(ydoc, ydocState);
		sample.applyUpdateV1 = performance.now() - start;
	}

	// EncodeV1
	{
		const start = performance.now();
		sample.updateV1 = encodeStateAsUpdate(ydoc)
		sample.encodeStateAsUpdateV1 = performance.now() - start;
	}

	// EncodeV2
	{
		const start = performance.now();
		sample.updateV2 = encodeStateAsUpdateV2(ydoc)
		sample.encodeStateAsUpdateV2 = performance.now() - start;
	}

	// ApplyV2
	{
		const ydoc = new Doc();
		const start = performance.now();
		applyUpdateV2(ydoc, sample.updateV2);
		sample.applyUpdateV2 = performance.now() - start;
		ydoc.destroy();
	}

	ydoc.destroy();

	return sample
};

const samples = [];
for (let i = 0; i < 3; i++) {
	const s = runTest();
	console.info(`Size v1: ${s.updateV1?.byteLength}, v2: ${s.updateV2?.byteLength}`);
	console.info(` - applyUpdateV1: ${s.applyUpdateV1}`);
	console.info(` - applyUpdateV2: ${s.applyUpdateV2}`);
	console.info(` - encodeStateAsUpdateV1: ${s.encodeStateAsUpdateV2}`);
	console.info(` - encodeStateAsUpdateV2: ${s.encodeStateAsUpdateV1}`);

}
```

And a [disco-board.json](https://drive.google.com/file/d/1Ie96v_0GYohxrDJHxUY-9BFEosF4g9Yt/view?usp=sharing)
</details>

**Comment by dmonad** [comment]
Parsing a 5mb document in 1.5 seconds seems about right. The CRDT benchmarks confirm this: https://github.com/dmonad/crdt-benchmarks/ (Yjs can parse 15MB of text in ~1.8 seconds - see B4x100).

I would ask why your document is that large? Just looking at the base64 encoded document, I can see a lot of repetition that could be avoided.

As I mentioned in the issue template, I'd like to keep GitHub issues for bug reports only. Could you please reopen your question in the discussion board if you want to discuss this in more detail? Maybe the community can help you. But you need to get into more detail of what you want to achieve, and what kind of data you are storing.

FYI: I offer architecture reviews and feedback to my sponsors. I suggest that you book a one-time meeting so we can discuss your specific needs (see tab one-time): https://github.com/sponsors/dmonad

**Comment by dmonad** [comment]
Since JavaScript is single-threaded, it doesn't make a difference whether Y.applyUpdate is sync or async. But you should definitely let workers handle heavy loads in your server implementation. You could employ something like a job-queue. But that's out of Yjs's scope.

**Comment by RubaXa** [comment]
> Since JavaScript is single-threaded, it doesn't make a difference whether Y.applyUpdate is sync or async.

You are absolutely right, JavaScript is single-threaded, but we can limit the execution of heavy operations by setting a budget for them.

If you're interested, here's a draft of a similar solution where the `readClientsStructRefs` loops have been replaced with asynchronous ones, which helps to offload the main thread:

https://gist.github.com/RubaXa/22e202eba47766a35a1c7235012d3dc2

However, as you can see, I removed the root transaction from `applyAsyncYUpdateToYDoc` (which was present in the synchronous version), which raises questions about how viable this idea is overall and whether it might break the document.

Of course, this approach is only needed for document initialization and only if we're dealing with a really large document.

Once again, thank you very much for your responses and work.

**Comment by dmonad** [comment]
I saw someone else doing something similar using generators `function * () {..}` to stop the update handler when the transaction takes too long. Generators are sync. You could also manually continue the function.

I have no plans to make the update function async (or to refactor it to a generator function), because that would ultimately hurt performance for "normal" use-cases. However, you are free to implement these functions yourself. That should be possible.

The code you are referring to looks problematic. For instance, you shouldn't feed async functions into a `ydoc.transact`. The async function finishes after the handler is run. So the events and cleanup happen before the function finishes execution.

**Comment by RubaXa** [comment]
Thank you so much for the detailed response

> using generators

I was also thinking about generators, so it was interesting to take a look at the real implementation

> The code you are referring to looks problematic

Yeah, that’s why I didn’t pursue it further—since it was already clear even at that stage that, even if it works, it’s more of a hack than a proper solution :]
