### ISSUE TITLE
How to combine with a grid?

### ISSUE THREAD

**Issue by COLABORATI** [yjs/yjs#95]
How would I combine yjs with a grid component, like e.g. http://js-grid.com ?
Is there already a binding for some grid component?
Thanks for your attention!
Here are some more grids / js tables - it would be great to see demos with the top rated ones to better understand how to implement ys with them: https://jspreadsheets.com/

**Comment by dmonad** [comment]
Hi @COLABORATI 
There are currently no grid-bindings. I would be happy to see a grid component, but I currently don't have the time to implement one. I'll leave this issue open, if anyone wants to hack a demo for this!
